package migrate

import (
	"context"
	"strings"
)

// SchemaSQL is the accumulated snapshot written to migrations/schema.sql:
// the DDL of a database with every migration applied, read back from
// sqlite_master so it is SQLite's own normalised text rather than the
// concatenation of the migration files.
func SchemaSQL(ctx context.Context, ms []Migration) (string, error) {
	d, err := Replay(ctx, ms)
	if err != nil {
		return "", err
	}
	defer d.Close()
	rows, err := d.QueryContext(ctx, `SELECT sql FROM sqlite_master
	  WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%' ORDER BY type DESC, name`)
	if err != nil {
		return "", err
	}
	defer rows.Close()
	var b strings.Builder
	b.WriteString("-- Generated by rastrillo migration generate; DO NOT EDIT.\n")
	b.WriteString("-- The schema every migration in this directory adds up to.\n\n")
	for rows.Next() {
		var s string
		if err := rows.Scan(&s); err != nil {
			return "", err
		}
		b.WriteString(strings.TrimSpace(s))
		b.WriteString(";\n\n")
	}
	return b.String(), rows.Err()
}
