package keyring

import (
	"crypto/ecdh"
	"crypto/rand"
	"crypto/x509"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

// TestRegenerateVectors writes testdata/golden.json and is skipped
// unless RASTRILLO_KEYRING_GEN=1. It exists to bootstrap the vectors
// file, not to refresh it: the committed file is hash-pinned by
// TestVectorsFileUntouched, and grant bytes are wire-format-forever —
// fix implementations, not vectors. (A gen command under keyring/gen
// would owe the docsite gate a reference page of its own; a skipped
// test regenerates without growing the package surface.)
func TestRegenerateVectors(t *testing.T) {
	if os.Getenv("RASTRILLO_KEYRING_GEN") != "1" {
		t.Skip("set RASTRILLO_KEYRING_GEN=1 to (re)generate testdata/golden.json")
	}

	r := Ring{Namespace: "kass"}

	seed, err := NewSeed()
	if err != nil {
		t.Fatalf("NewSeed: %v", err)
	}
	prf := make([]byte, 32)
	if _, err := rand.Read(prf); err != nil {
		t.Fatalf("rand: %v", err)
	}
	memberPriv, err := ecdh.P256().GenerateKey(rand.Reader)
	if err != nil {
		t.Fatalf("generate member key: %v", err)
	}
	pkcs8, err := x509.MarshalPKCS8PrivateKey(memberPriv)
	if err != nil {
		t.Fatalf("marshal pkcs8: %v", err)
	}

	contentKey := r.ContentKey(seed)
	wrapped, err := r.WrapSeed(prf, seed)
	if err != nil {
		t.Fatalf("WrapSeed: %v", err)
	}
	grant, err := r.Grant(memberPriv.PublicKey().Bytes(), contentKey)
	if err != nil {
		t.Fatalf("Grant: %v", err)
	}

	b64 := base64.StdEncoding.EncodeToString
	var g goldenFile
	g.Provenance = "generated by TestRegenerateVectors (RASTRILLO_KEYRING_GEN=1), 2026-08-23; hash-pinned by TestVectorsFileUntouched — fix implementations, not vectors"
	g.Namespace = "kass"
	g.Strings.PRFSalt = r.PRFSalt()
	g.Strings.Content = "kass/content/v1"
	g.Strings.Wrap = "kass/wrap/v1"
	g.Strings.Grant = "kass/grant/v1"
	g.Seed = b64(seed)
	g.ContentKey = b64(contentKey)
	g.PRF = b64(prf)
	g.WrapKey = b64(r.WrapKey(prf))
	g.WrappedSeed = b64(wrapped)
	g.Member.BoxPrivD = hex.EncodeToString(memberPriv.Bytes())
	g.Member.BoxPrivPKCS8 = b64(pkcs8)
	g.Member.BoxPub = b64(memberPriv.PublicKey().Bytes())
	g.Grant = b64(grant)

	out, err := json.MarshalIndent(g, "", "  ")
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	if err := os.MkdirAll("testdata", 0o755); err != nil {
		t.Fatalf("mkdir testdata: %v", err)
	}
	if err := os.WriteFile(filepath.Join("testdata", "golden.json"), append(out, '\n'), 0o644); err != nil {
		t.Fatalf("write golden.json: %v", err)
	}
}
