// Code generated by rastrillo generate; DO NOT EDIT.

// Package announcementsstore is the mergeable store for the
// announcements resource: the exclusive (sqlc) stores' exact method
// surface, implemented over the eventlog package. Every record is one
// event stream ("announcements/<id>"); a create/update appends an
// event, a delete appends a tombstone, and every read derives live
// state by replaying the merged history — no table of this resource's
// own, no materialized cache (replay is cheap until proven otherwise).
//
// Two recorded caveats, both deliberate:
//   - Every event's actor is stamped "app"; threading Ctx.Actor into
//     store mutations is an additive follow-up (today every generated
//     mutation is consent-gated upstream).
//   - Record ids are writer-local: Create allocates max(existing)+1,
//     race-free under the single-writer SQLite pool both db paths
//     enforce. Cross-writer id namespacing belongs to the platform
//     transport design; this allocator is the first thing it replaces.
package announcementsstore

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"sort"
	"strconv"
	"strings"

	"amadan.net/rastrillo/rastrillo/eventlog"
)

// streamPrefix namespaces this resource's streams in the shared
// eventlog table: record <id> lives at "announcements/<id>".
const streamPrefix = "announcements/"

// actor is stamped on every event this store appends — see the
// package doc's Ctx.Actor caveat.
const actor = "app"

// Announcement is the derived read model — the same shape sqlc
// generates for an exclusive resource.
type Announcement struct {
	ID        int64
	Title     string
	Body      string
	CreatedAt string
	UpdatedAt string
}

type Queries struct {
	db *sql.DB
}

func New(db *sql.DB) *Queries {
	return &Queries{db: db}
}

// open resolves the database's durable writer identity (lazily, per
// call — a one-row SELECT) and binds an eventlog.Log to it.
func (q *Queries) open(ctx context.Context) (*eventlog.Log, error) {
	writer, err := eventlog.LocalWriter(ctx, q.db)
	if err != nil {
		return nil, err
	}
	return eventlog.Open(q.db, writer)
}

// payload is the JSON shape of every created/updated event: pointer
// fields, omitted when nil, so a created event carries every field and
// an updated event only its own group's — an absent field leaves the
// derived value untouched.
type payload struct {
	Title     *string `json:"title,omitempty"`
	Body      *string `json:"body,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
}

// state is the fold state for one stream: the derived row, whether a
// tombstone was seen, and the first decode error (which poisons the
// fold rather than deriving half a record).
type state struct {
	row  Announcement
	dead bool
	err  error
}

// reduce is the pure fold eventlog.Derive runs: created/updated apply
// their payload's present fields ("created" also seeds updated_at from
// created_at, the same both-timestamps-at-once rule the exclusive
// INSERT uses); "deleted" is a tombstone, and dead stays dead.
func reduce(s state, ev eventlog.Event) state {
	if s.err != nil || s.dead {
		return s
	}
	switch ev.Kind {
	case "created", "updated":
		var p payload
		if err := json.Unmarshal(ev.Payload, &p); err != nil {
			s.err = fmt.Errorf("announcementsstore: decode %s event on %s: %w", ev.Kind, ev.Stream, err)
			return s
		}
		if p.Title != nil {
			s.row.Title = *p.Title
		}
		if p.Body != nil {
			s.row.Body = *p.Body
		}
		if p.CreatedAt != nil {
			s.row.CreatedAt = *p.CreatedAt
			s.row.UpdatedAt = *p.CreatedAt
		}
		if p.UpdatedAt != nil {
			s.row.UpdatedAt = *p.UpdatedAt
		}
	case "deleted":
		s.dead = true
	}
	return s
}

// derive folds one stream's merged history into its live row; ok is
// false for an empty or tombstoned stream.
func derive(id int64, events []eventlog.Event) (Announcement, bool, error) {
	if len(events) == 0 {
		return Announcement{}, false, nil
	}
	s := eventlog.Derive(events, reduce)
	if s.err != nil {
		return Announcement{}, false, s.err
	}
	if s.dead {
		return Announcement{}, false, nil
	}
	s.row.ID = id
	return s.row, true, nil
}

// streamID parses the record id out of a stream name.
func streamID(stream string) (int64, error) {
	id, err := strconv.ParseInt(strings.TrimPrefix(stream, streamPrefix), 10, 64)
	if err != nil {
		return 0, fmt.Errorf("announcementsstore: bad stream %q: %w", stream, err)
	}
	return id, nil
}

// live derives every live record, sorted the way the exclusive List
// orders rows (created_at DESC, id DESC — RFC3339 strings compare
// correctly as text, exactly as they do in SQLite).
func (q *Queries) live(ctx context.Context) ([]Announcement, error) {
	log, err := q.open(ctx)
	if err != nil {
		return nil, err
	}
	events, err := log.EventsByPrefix(ctx, streamPrefix)
	if err != nil {
		return nil, err
	}
	byID := map[int64][]eventlog.Event{}
	var ids []int64
	for _, ev := range events {
		id, err := streamID(ev.Stream)
		if err != nil {
			return nil, err
		}
		if _, ok := byID[id]; !ok {
			ids = append(ids, id)
		}
		byID[id] = append(byID[id], ev)
	}
	var rows []Announcement
	for _, id := range ids {
		row, ok, err := derive(id, byID[id])
		if err != nil {
			return nil, err
		}
		if ok {
			rows = append(rows, row)
		}
	}
	sort.Slice(rows, func(i, j int) bool {
		if rows[i].CreatedAt != rows[j].CreatedAt {
			return rows[i].CreatedAt > rows[j].CreatedAt
		}
		return rows[i].ID > rows[j].ID
	})
	return rows, nil
}

// matches mirrors the exclusive store's WHERE clauses: an empty search
// matches everything, otherwise a case-insensitive substring over the
// searchable list columns (SQLite LIKE's own ASCII fold).
func matches(n Announcement, search string) bool {
	if search != "" {
		s := strings.ToLower(search)
		if !strings.Contains(strings.ToLower(n.Title), s) {
			return false
		}
	}
	return true
}

// pageWindow applies the SQL LIMIT/OFFSET page window.
func pageWindow(rows []Announcement, offset, limit int64) []Announcement {
	if offset < 0 {
		offset = 0
	}
	if offset >= int64(len(rows)) {
		return nil
	}
	rows = rows[offset:]
	if limit >= 0 && limit < int64(len(rows)) {
		rows = rows[:limit]
	}
	return rows
}

type ListAnnouncementsParams struct {
	Search     string
	PageOffset int64
	PageLimit  int64
}

func (q *Queries) ListAnnouncements(ctx context.Context, arg ListAnnouncementsParams) ([]Announcement, error) {
	rows, err := q.live(ctx)
	if err != nil {
		return nil, err
	}
	var out []Announcement
	for _, n := range rows {
		if matches(n, arg.Search) {
			out = append(out, n)
		}
	}
	return pageWindow(out, arg.PageOffset, arg.PageLimit), nil
}

func (q *Queries) CountAnnouncements(ctx context.Context, search string) (int64, error) {
	rows, err := q.live(ctx)
	if err != nil {
		return 0, err
	}
	var total int64
	for _, n := range rows {
		if matches(n, search) {
			total++
		}
	}
	return total, nil
}

func (q *Queries) GetAnnouncement(ctx context.Context, id int64) (Announcement, error) {
	log, err := q.open(ctx)
	if err != nil {
		return Announcement{}, err
	}
	events, err := log.Events(ctx, streamPrefix+strconv.FormatInt(id, 10))
	if err != nil {
		return Announcement{}, err
	}
	row, ok, err := derive(id, events)
	if err != nil {
		return Announcement{}, err
	}
	if !ok {
		return Announcement{}, sql.ErrNoRows
	}
	return row, nil
}

type CreateAnnouncementParams struct {
	Title string
	Body  string
	Now   string
}

func (q *Queries) CreateAnnouncement(ctx context.Context, arg CreateAnnouncementParams) (int64, error) {
	log, err := q.open(ctx)
	if err != nil {
		return 0, err
	}
	// Writer-local id allocation (see the package doc's caveat):
	// max(existing id in this resource's streams)+1, race-free under
	// the single-writer SQLite pool.
	events, err := log.EventsByPrefix(ctx, streamPrefix)
	if err != nil {
		return 0, err
	}
	var id int64
	for _, ev := range events {
		evID, err := streamID(ev.Stream)
		if err != nil {
			return 0, err
		}
		if evID > id {
			id = evID
		}
	}
	id++
	p := payload{
		Title:     &arg.Title,
		Body:      &arg.Body,
		CreatedAt: &arg.Now,
	}
	if _, err := log.Append(ctx, streamPrefix+strconv.FormatInt(id, 10), "created", actor, p); err != nil {
		return 0, err
	}
	return id, nil
}

type UpdateAnnouncementBasicsParams struct {
	Title string
	Body  string
	Now   string
	ID    int64
}

func (q *Queries) UpdateAnnouncementBasics(ctx context.Context, arg UpdateAnnouncementBasicsParams) error {
	log, err := q.open(ctx)
	if err != nil {
		return err
	}
	stream := streamPrefix + strconv.FormatInt(arg.ID, 10)
	events, err := log.Events(ctx, stream)
	if err != nil {
		return err
	}
	_, ok, err := derive(arg.ID, events)
	if err != nil {
		return err
	}
	if !ok {
		// Mirror the exclusive UPDATE: a missing record is a no-op,
		// never an appended event on a stream with no live record.
		return nil
	}
	p := payload{
		Title:     &arg.Title,
		Body:      &arg.Body,
		UpdatedAt: &arg.Now,
	}
	_, err = log.Append(ctx, stream, "updated", actor, p)
	return err
}

func (q *Queries) DeleteAnnouncement(ctx context.Context, id int64) error {
	log, err := q.open(ctx)
	if err != nil {
		return err
	}
	stream := streamPrefix + strconv.FormatInt(id, 10)
	events, err := log.Events(ctx, stream)
	if err != nil {
		return err
	}
	_, ok, err := derive(id, events)
	if err != nil {
		return err
	}
	if !ok {
		return nil
	}
	// Delete appends a tombstone event rather than a DELETE; derive
	// skips dead ids from here on.
	_, err = log.Append(ctx, stream, "deleted", actor, struct{}{})
	return err
}
