// Code generated by rastrillo generate; DO NOT EDIT.
package announcementsstore

import "github.com/carlosframework/rastrillo/eventlog"

// Migrations re-exports the eventlog schema for Options.Migrations: a
// mergeable resource has no table of its own — every record is an
// eventlog stream. Idempotent, so two mergeable resources appending it
// twice is harmless.
var Migrations = eventlog.Migrations
