// rastrillo migration — the schema-change tooling.
//
// The group is a noun on purpose. `rastrillo migrate`, typed bare,
// reads as "apply my migrations now", and this CLI deliberately never
// applies: migrations run at boot, because a hibernating route has no
// operator moment between a new binary landing and the activator
// exec'ing it. The one exception is `baseline`, which is manual by
// design.
package main

import (
	"context"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/carlosframework/rastrillo/db"
	"github.com/carlosframework/rastrillo/migrate"
	"github.com/carlosframework/rastrillo/migrate/dump"
)

func runMigration(args []string) error {
	if len(args) == 0 {
		return errors.New("usage: rastrillo migration <generate|new|status|check|baseline> [dir]")
	}
	sub, rest := args[0], args[1:]
	switch sub {
	case "generate":
		return migrationGenerate(rest)
	case "check":
		return migrationCheck(rest)
	case "new":
		return migrationNew(rest)
	case "status":
		return migrationStatus(rest)
	case "baseline":
		return migrationBaseline(rest)
	default:
		return fmt.Errorf("unknown migration subcommand %q (generate, check, new, status, baseline are available)", sub)
	}
}

// appPackage locates the app's package: the single directory under
// internal/ that is not the <name>test harness. rastrillo new
// scaffolds exactly one, and dev.go already assumes the same
// single-app shape for cmd/.
func appPackage(dir string) (importPath, pkgName string, err error) {
	mod, err := modulePath(dir)
	if err != nil {
		return "", "", err
	}
	entries, err := os.ReadDir(filepath.Join(dir, "internal"))
	if err != nil {
		return "", "", fmt.Errorf("no internal/ directory in %s: %w", dir, err)
	}
	var found []string
	for _, e := range entries {
		if e.IsDir() && !strings.HasSuffix(e.Name(), "test") {
			found = append(found, e.Name())
		}
	}
	sort.Strings(found)
	if len(found) != 1 {
		return "", "", fmt.Errorf("expected exactly one app package under %s/internal, found %v", dir, found)
	}
	return mod + "/internal/" + found[0], found[0], nil
}

// loaderDir is the throwaway package `loadPayload` writes into the
// app module. No leading dot or underscore: the go tool skips
// directories named that way, so `go run ./loaderDir` would silently
// find nothing to run.
const loaderDir = "rastrillo_migration_dump"

const loaderTemplate = `// Code generated by rastrillo migration; removed immediately after use.
package main

import (
	app %q

	"github.com/carlosframework/rastrillo/migrate/dump"
)

func main() { dump.Main(app.Schema.All(), app.BootSchema.All(), app.Models) }
`

// loadPayload compiles and runs a throwaway program inside the app
// module. rastrillo cannot import the app's models directly — it is a
// separate binary — and parsing models.go to reimplement GORM's
// tag-to-DDL mapping would duplicate GORM and drift from it.
//
// It shells out to the ambient `go` toolchain with no environment
// overrides of its own: a real developer has a real network and a
// real module cache, and hardcoding proxy/sum settings here would
// only be right for this repo's sandboxed tests, which set them on
// their own exec.Command instead (see migration_test.go).
func loadPayload(dir string) (dump.Payload, error) {
	var p dump.Payload
	importPath, _, err := appPackage(dir)
	if err != nil {
		return p, err
	}
	ldir := filepath.Join(dir, loaderDir)
	if err := os.MkdirAll(ldir, 0o755); err != nil {
		return p, err
	}
	defer os.RemoveAll(ldir)

	body := fmt.Sprintf(loaderTemplate, importPath)
	if err := os.WriteFile(filepath.Join(ldir, "main.go"), []byte(body), 0o644); err != nil {
		return p, err
	}

	cmd := exec.Command("go", "run", "./"+loaderDir)
	cmd.Dir = dir
	var stderr strings.Builder
	cmd.Stderr = &stderr
	out, err := cmd.Output()
	if err != nil {
		// The compiler's own message is the only thing a developer
		// sees when their app doesn't build — wrapping it in a
		// generic "loader failed" would send them hunting for a bug
		// in rastrillo instead of the app.
		return p, fmt.Errorf("loading the app's models failed — the app must compile:\n%s", stderr.String())
	}
	if err := json.Unmarshal(out, &p); err != nil {
		return p, fmt.Errorf("could not parse the loader's output: %w", err)
	}
	return p, nil
}

// openExistingDB opens a database that must already be there.
//
// db.Open creates the file when it is absent, and for these two
// commands that is never what the operator meant: a typo'd path had
// baseline print "stamped" over a brand-new empty database while the
// real one carried on refusing to boot, and had status report a tidy,
// empty ledger for a database it had never opened. Both are commands
// you reach for while recovering, when a reassuring wrong answer is
// the most expensive kind.
func openExistingDB(path string) (*db.DB, error) {
	if _, err := os.Stat(path); err != nil {
		return nil, fmt.Errorf("no database at %q: %w\n"+
			"baseline and status both read a database that already exists — neither creates one. "+
			"Check the path.", path, err)
	}
	return db.Open(path, nil)
}

func migrationsDir(dir string) (string, error) {
	_, pkg, err := appPackage(dir)
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "internal", pkg, "migrations"), nil
}

func dirArg(args []string) string {
	for _, a := range args {
		if !strings.HasPrefix(a, "-") {
			return a
		}
	}
	return "."
}

func migrationCheck(args []string) error {
	dir := dirArg(args)
	p, err := loadPayload(dir)
	if err != nil {
		return err
	}
	if len(p.Changes) == 0 {
		fmt.Println("rastrillo migration check: models and migrations agree")
		return nil
	}
	var b strings.Builder
	b.WriteString("models and migrations disagree:\n")
	for _, c := range p.Changes {
		b.WriteString("  " + strings.TrimSpace(c.SQL) + "\n")
	}
	b.WriteString("\nrun: rastrillo migration generate")
	return errors.New(b.String())
}

func migrationGenerate(args []string) error {
	// A FlagSet, like every other subcommand here. The hand-rolled
	// scan this replaced compared each argument to the exact string
	// "--allow-destructive", so the single-dash spelling `flag` itself
	// accepts everywhere else in this CLI was read as a directory name
	// and silently ignored — generate then refused the change and gave
	// the user no way to see why.
	fs := flag.NewFlagSet("generate", flag.ContinueOnError)
	allowDestructive := fs.Bool("allow-destructive", false,
		"write the migration even though it drops data")
	if err := fs.Parse(args); err != nil {
		return err
	}
	dir := dirArg(fs.Args())
	p, err := loadPayload(dir)
	if err != nil {
		return err
	}
	if len(p.Changes) == 0 {
		fmt.Println("rastrillo migration generate: nothing to do")
		return nil
	}

	var destructive []string
	for _, c := range p.Changes {
		if c.Destructive {
			destructive = append(destructive, strings.TrimSpace(c.SQL))
		}
	}
	if len(destructive) > 0 && !*allowDestructive {
		return fmt.Errorf(
			"this change drops data:\n  %s\n\n"+
				"Re-run with --allow-destructive if that is what you want.\n"+
				"If you meant to rename rather than drop, write it by hand instead:\n"+
				"  rastrillo migration new rename_something\n"+
				"  ALTER TABLE t RENAME COLUMN old TO new;",
			strings.Join(destructive, "\n  "))
	}

	mdir, err := migrationsDir(dir)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(mdir, 0o755); err != nil {
		return err
	}
	name, err := nextMigrationName(mdir, describe(p.Changes))
	if err != nil {
		return err
	}
	var body strings.Builder
	for _, c := range p.Changes {
		body.WriteString(strings.TrimSpace(c.SQL))
		body.WriteString("\n\n")
	}
	if err := os.WriteFile(filepath.Join(mdir, name), []byte(body.String()), 0o644); err != nil {
		return err
	}
	fmt.Printf("rastrillo migration generate: wrote %s\n", filepath.Join(mdir, name))

	// schema.sql must reflect the migration just written, so recompute
	// it with the new file in place. This is a second full `go run` of
	// the app module — go:embed captures the migrations directory at
	// compile time, so the first loader's build can't have seen a file
	// that didn't exist yet.
	p2, err := loadPayload(dir)
	if err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(mdir, "schema.sql"), []byte(p2.Schema), 0o644); err != nil {
		return err
	}
	fmt.Printf("rastrillo migration generate: refreshed %s\n", filepath.Join(mdir, "schema.sql"))
	return nil
}

// describe names a migration after what it does, so the filename is
// readable in a diff without opening it.
//
// It cannot simply grep for "ADD COLUMN": gormlite's AddColumn (like
// upstream GORM's) emits "ALTER TABLE ... ADD <col> <type>", never
// the word COLUMN, and DropColumn/DropIndex have no DDL keyword to
// grep for at all — SQLite cannot ALTER TABLE DROP COLUMN, so gormlite
// rebuilds the table (CREATE TABLE ...__temp, INSERT INTO, DROP TABLE,
// then ALTER TABLE ... RENAME TO) and the recorder captures every
// statement in that rebuild. The RENAME TO that ends a rebuild is
// checked first, ahead of CREATE TABLE, precisely because a rebuild's
// own synthetic CREATE TABLE ...__temp would otherwise win the naive
// first-match and mislabel a dropped column as a created table.
func describe(changes []migrate.Change) string {
	for _, c := range changes {
		if strings.Contains(strings.ToUpper(c.SQL), "RENAME TO") {
			return "drop_column_" + renamedTable(c.SQL)
		}
	}
	for _, c := range changes {
		u := strings.ToUpper(c.SQL)
		switch {
		case strings.HasPrefix(u, "CREATE TABLE"):
			return "create_" + tableIn(c.SQL)
		case strings.HasPrefix(u, "ALTER TABLE") && strings.Contains(u, "ADD"):
			return "alter_" + tableIn(c.SQL)
		case strings.HasPrefix(u, "DROP TABLE"):
			return "drop_" + tableIn(c.SQL)
		}
	}
	return "schema"
}

func tableIn(sqlText string) string {
	fields := strings.Fields(strings.ReplaceAll(sqlText, "`", " "))
	for i, f := range fields {
		if !strings.EqualFold(f, "TABLE") {
			continue
		}
		// gormlite's DropTable emits "DROP TABLE IF EXISTS <name>" —
		// skip the "IF [NOT] EXISTS" clause rather than returning "IF".
		j := i + 1
		for j < len(fields) && (strings.EqualFold(fields[j], "IF") ||
			strings.EqualFold(fields[j], "NOT") || strings.EqualFold(fields[j], "EXISTS")) {
			j++
		}
		if j < len(fields) {
			return strings.Trim(strings.ToLower(fields[j]), `"'();`)
		}
	}
	return "schema"
}

// renamedTable reads the destination name off an "... RENAME TO x"
// statement — the real table name once gormlite's rebuild finishes —
// rather than tableIn's "TABLE"-relative lookup, which on this
// statement shape would return the transient "...__temp" source name.
func renamedTable(sqlText string) string {
	fields := strings.Fields(strings.ReplaceAll(sqlText, "`", " "))
	for i, f := range fields {
		if strings.EqualFold(f, "TO") && i+1 < len(fields) {
			return strings.Trim(strings.ToLower(fields[i+1]), `"'();`)
		}
	}
	return tableIn(sqlText)
}

func nextMigrationName(mdir, label string) (string, error) {
	entries, err := os.ReadDir(mdir)
	if err != nil && !os.IsNotExist(err) {
		return "", err
	}
	n := 0
	for _, e := range entries {
		if len(e.Name()) < 4 {
			continue
		}
		var got int
		if _, err := fmt.Sscanf(e.Name()[:4], "%04d", &got); err == nil && got > n {
			n = got
		}
	}
	return fmt.Sprintf("%04d_%s.sql", n+1, label), nil
}

// migrationNameOK matches the same shape FromFS requires of a
// migration file's stem (migrate/set.go's fileName), so a name
// `migration new` accepts is never one FromFS then refuses to load.
var migrationNameOK = regexp.MustCompile(`^[a-z0-9_]+$`)

// migrationNew writes a numbered stub for a hand-written migration —
// the case `generate` cannot cover because a rename is
// indistinguishable, at the SQL-diff level, from a drop plus an add.
func migrationNew(args []string) error {
	if len(args) == 0 {
		return errors.New("usage: rastrillo migration new <name> [dir]")
	}
	name := args[0]
	if !migrationNameOK.MatchString(name) {
		return fmt.Errorf("migration name %q must be lowercase letters, digits and underscores", name)
	}
	dir := dirArg(args[1:])
	mdir, err := migrationsDir(dir)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(mdir, 0o755); err != nil {
		return err
	}
	file, err := nextMigrationName(mdir, name)
	if err != nil {
		return err
	}
	stub := `-- ` + name + `
--
-- Write the SQL this migration should run. It applies once, at boot,
-- inside its own transaction, and is never re-run or reversed.
--
-- Renames belong here rather than in a generated migration, because a
-- rename is indistinguishable from a drop plus an add:
--   ALTER TABLE notes RENAME COLUMN title TO heading;
`
	path := filepath.Join(mdir, file)
	if err := os.WriteFile(path, []byte(stub), 0o644); err != nil {
		return err
	}
	fmt.Printf("rastrillo migration new: wrote %s\n", path)
	return nil
}

// migrationStatus answers, for one real database, the three questions
// design §9 asks of it: what the ledger has recorded, whether any
// recorded migration's checksum differs from the file it came from
// (the reason a boot refuses), and what is still waiting — both senses
// of waiting, a migration in BootSchema the ledger has never seen, and
// a model change nobody has generated a migration for yet.
//
// All three come from data status already holds: the ledger it just
// read, and p.Boot, which carries each boot migration's SQL precisely
// so a checksum can be computed from it.
func migrationStatus(args []string) error {
	fs := flag.NewFlagSet("status", flag.ContinueOnError)
	dbPath := fs.String("db", "", "path to the app's SQLite database")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if *dbPath == "" {
		return errors.New("rastrillo migration status needs --db <path>: it reports what a real database has applied")
	}
	dir := dirArg(fs.Args())
	p, err := loadPayload(dir)
	if err != nil {
		return err
	}

	d, err := openExistingDB(*dbPath)
	if err != nil {
		return err
	}
	defer d.Close()
	ctx := context.Background()
	conn, err := d.Writer().Conn(ctx)
	if err != nil {
		return err
	}
	defer conn.Close()

	// A missing ledger table is the ordinary "never booted this
	// version yet" case and gets a friendly line instead of an error.
	// Checked by name against sqlite_master rather than by running the
	// SELECT below and treating any failure as "no ledger" — that
	// would just as happily swallow a real problem (a corrupt file, a
	// ledger whose columns don't match what this binary expects) and
	// report success on a database nobody should trust.
	var ledgerExists int
	if err := conn.QueryRowContext(ctx,
		"SELECT count(*) FROM sqlite_master WHERE type = 'table' AND name = 'rastrillo_migrations'",
	).Scan(&ledgerExists); err != nil {
		return err
	}
	if ledgerExists == 0 {
		fmt.Println("no migration ledger in this database — it has never been booted with this version")
		return nil
	}

	// checksum, not just id and applied_at: design §9 puts "does any
	// applied migration's checksum differ from its file?" among the
	// questions status answers, and it is the one an operator is most
	// likely to be asking. An app that has started refusing to boot on
	// an edited migration used to run status, see a tidy list and no
	// complaint, and conclude the database was fine.
	rows, err := conn.QueryContext(ctx,
		"SELECT id, applied_at, checksum FROM rastrillo_migrations ORDER BY id")
	if err != nil {
		return err
	}
	type row struct{ at, sum string }
	ledger := map[string]row{}
	var ids []string
	for rows.Next() {
		var id string
		var r row
		if err := rows.Scan(&id, &r.at, &r.sum); err != nil {
			rows.Close()
			return err
		}
		ids = append(ids, id)
		ledger[id] = r
	}
	if err := rows.Err(); err != nil {
		rows.Close()
		return err
	}
	rows.Close()

	fmt.Println("applied:")
	for _, id := range ids {
		fmt.Printf("  %-40s %s\n", id, ledger[id].at)
	}

	// p.Boot is the app's composed boot set and carries each
	// migration's SQL, not just its ID — it is there so baseline can
	// checksum what it stamps, and it is exactly what both of the
	// answers below need. Nothing here reads the database a second
	// time.
	var edited, pending []string
	for _, m := range p.Boot {
		l, ok := ledger[m.ID]
		if !ok {
			pending = append(pending, m.ID)
			continue
		}
		// Same condition Apply refuses on. A Go migration (SQL == "")
		// is stamped with the checksum of an empty string, so there is
		// nothing to compare.
		if m.SQL != "" && l.sum != migrate.Checksum(m.SQL) {
			edited = append(edited, m.ID)
		}
	}
	if len(edited) > 0 {
		fmt.Println("\nEDITED AFTER APPLYING — this app will refuse to boot against this database:")
		for _, id := range edited {
			fmt.Printf("  %s\n", id)
		}
		fmt.Println("  The file's SQL no longer matches what the ledger recorded. Restore the file: " +
			"a migration is immutable once applied. If the change is wanted, add a new migration.")
	}
	if len(pending) > 0 {
		fmt.Println("\npending (in BootSchema, not in this ledger — the next boot applies these):")
		for _, id := range pending {
			fmt.Printf("  %s\n", id)
		}
	}
	// A second, unrelated sense of "pending": not a migration waiting
	// to be applied, but one that has not been written yet.
	if len(p.Changes) > 0 {
		fmt.Println("\nnot yet generated (models and migrations disagree — run rastrillo migration generate):")
		for _, c := range p.Changes {
			fmt.Printf("  %s\n", strings.TrimSpace(c.SQL))
		}
	}
	return nil
}

// throughHint is a best-effort suggestion for the likely typo of
// leaving off the namespace — "0001_init" instead of
// "sessions/0001_init" — plausible from an operator at 3am reading
// auth/store.go's recovery steps, which name the bare migration
// filename in prose before giving the fully-qualified --through
// value. IDs are namespace-qualified and case is never normalised: a
// bare suffix can match more than one namespace (an app's own
// 0001_init and a subsystem's both exist in most boot sets), and
// guessing wrong here would stamp the wrong prefix — the precise harm
// --through validation exists to prevent — so this only ever adds a
// sentence to the error, it never changes what gets matched or
// stamped.
func throughHint(through string, set []migrate.Migration) string {
	var matches []string
	for _, m := range set {
		if strings.HasSuffix(m.ID, "/"+through) {
			matches = append(matches, m.ID)
		}
	}
	switch len(matches) {
	case 0:
		return ""
	case 1:
		return fmt.Sprintf(" (--through must be namespace-qualified — did you mean %q?)", matches[0])
	default:
		return fmt.Sprintf(" (--through must be namespace-qualified — %s all end in \"/%s\", so name one of them)",
			strings.Join(matches, ", "), through)
	}
}

// migrationBaseline stamps a database's ledger by hand, without
// running anything — the one recovery path for a deployed schema
// Apply refused to adopt because it doesn't match the migration set,
// and the procedure auth/store.go's doc comment documents for
// recovering a database that predates the sessions core:
//
//	rastrillo migration baseline --db <path> --through sessions/0001_init
//
// That ID is not in this app's own namespace, so baseline goes
// through the same go run loader generate and check use (loadPayload)
// to get app.BootSchema.All() — the composed, ordered set the app
// actually applies at boot — rather than reading the app's own
// migrations/ directory off disk the way an earlier version of this
// command did. Two things were tried and rejected instead:
//
//   - Reading the disk directory only ever sees the app's own
//     namespace. It cannot discover a framework subsystem's
//     migrate.Set at all — sessions/0001_init doesn't exist as a
//     file anywhere reachable from the app's migrations directory —
//     so the documented recovery above errored with "not a known
//     migration id" no matter what.
//   - Having this CLI import sessions/auth/etc. directly instead
//     doesn't fix that: cmd/rastrillo is in the same module and
//     could, but migrate.Stamp walks a single ordered list and stops
//     after --through, and the CLI has no way to know the *order* an
//     app composed those packages in (migrate.Merge's argument order,
//     chosen in the app's own Go source, e.g.
//     migrate.Merge(sessions.Schema, auth.Schema)). Guessing that
//     order and stamping the wrong prefix is exactly the harm
//     --through validation exists to prevent — for the sessions/auth
//     recovery specifically, it would mean auth's backfill migration
//     never runs and looks like it already did, signing out every
//     user.
//
// The cost is that baseline now requires the app to compile, which it
// didn't before. That's the right trade: the alternative is stamping
// the wrong prefix, and an operator reaching for baseline is
// recovering a *database* — the binary that refused to boot compiled
// fine.
//
// --through is validated against BootSchema before anything is
// written: migrate.Stamp itself does not check through against the
// migration list, so an ID that matches nothing would silently fall
// through to stamping every migration. Failing loudly here, before
// the database is even opened, is cheaper than that.
func migrationBaseline(args []string) error {
	fs := flag.NewFlagSet("baseline", flag.ContinueOnError)
	dbPath := fs.String("db", "", "path to the app's SQLite database")
	through := fs.String("through", "", "stop stamping after this migration ID")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if *dbPath == "" {
		return errors.New("rastrillo migration baseline needs --db <path>")
	}
	dir := dirArg(fs.Args())

	p, err := loadPayload(dir)
	if err != nil {
		return err
	}
	set := p.Boot
	if *through != "" {
		found := false
		ids := make([]string, 0, len(set))
		for _, m := range set {
			ids = append(ids, m.ID)
			if m.ID == *through {
				found = true
			}
		}
		if !found {
			return fmt.Errorf(
				"--through %q does not name a migration in this app's boot set%s; "+
					"stamping would otherwise silently fall through to every migration instead of "+
					"stopping partway. Known ids:\n  %s",
				*through, throughHint(*through, set), strings.Join(ids, "\n  "))
		}
	}

	d, err := openExistingDB(*dbPath)
	if err != nil {
		return err
	}
	defer d.Close()
	ctx := context.Background()
	conn, err := d.Writer().Conn(ctx)
	if err != nil {
		return err
	}
	defer conn.Close()
	if _, err := conn.ExecContext(ctx, migrate.LedgerDDL); err != nil {
		return err
	}
	if err := migrate.Stamp(ctx, conn, set, *through); err != nil {
		return err
	}
	fmt.Printf("rastrillo migration baseline: stamped %s\n", *dbPath)
	return nil
}
