// rastrillo migration — the schema-change tooling.
//
// The group is a noun on purpose. `rastrillo migrate`, typed bare,
// reads as "apply my migrations now", and this CLI deliberately never
// applies: migrations run at boot, because a hibernating route has no
// operator moment between a new binary landing and the activator
// exec'ing it. The one exception is `baseline`, which is manual by
// design.
package main

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"github.com/carlosframework/rastrillo/migrate"
	"github.com/carlosframework/rastrillo/migrate/dump"
)

func runMigration(args []string) error {
	if len(args) == 0 {
		return errors.New("usage: rastrillo migration <generate|new|status|check|baseline> [dir]")
	}
	sub, rest := args[0], args[1:]
	switch sub {
	case "generate":
		return migrationGenerate(rest)
	case "check":
		return migrationCheck(rest)
	default:
		// "new", "status" and "baseline" are the rest of the group —
		// they land in a follow-up change. Naming them here (rather
		// than a bare "unknown subcommand") tells a developer who
		// reads the usage text and tries one that it is coming, not
		// a typo.
		return fmt.Errorf("unknown migration subcommand %q (generate, check are available; new, status, baseline land in a follow-up)", sub)
	}
}

// appPackage locates the app's package: the single directory under
// internal/ that is not the <name>test harness. rastrillo new
// scaffolds exactly one, and dev.go already assumes the same
// single-app shape for cmd/.
func appPackage(dir string) (importPath, pkgName string, err error) {
	mod, err := modulePath(dir)
	if err != nil {
		return "", "", err
	}
	entries, err := os.ReadDir(filepath.Join(dir, "internal"))
	if err != nil {
		return "", "", fmt.Errorf("no internal/ directory in %s: %w", dir, err)
	}
	var found []string
	for _, e := range entries {
		if e.IsDir() && !strings.HasSuffix(e.Name(), "test") {
			found = append(found, e.Name())
		}
	}
	sort.Strings(found)
	if len(found) != 1 {
		return "", "", fmt.Errorf("expected exactly one app package under %s/internal, found %v", dir, found)
	}
	return mod + "/internal/" + found[0], found[0], nil
}

// loaderDir is the throwaway package `loadPayload` writes into the
// app module. No leading dot or underscore: the go tool skips
// directories named that way, so `go run ./loaderDir` would silently
// find nothing to run.
const loaderDir = "rastrillo_migration_dump"

const loaderTemplate = `// Code generated by rastrillo migration; removed immediately after use.
package main

import (
	app %q

	"github.com/carlosframework/rastrillo/migrate/dump"
)

func main() { dump.Main(app.Schema.All(), app.Models) }
`

// loadPayload compiles and runs a throwaway program inside the app
// module. rastrillo cannot import the app's models directly — it is a
// separate binary — and parsing models.go to reimplement GORM's
// tag-to-DDL mapping would duplicate GORM and drift from it.
//
// It shells out to the ambient `go` toolchain with no environment
// overrides of its own: a real developer has a real network and a
// real module cache, and hardcoding proxy/sum settings here would
// only be right for this repo's sandboxed tests, which set them on
// their own exec.Command instead (see migration_test.go).
func loadPayload(dir string) (dump.Payload, error) {
	var p dump.Payload
	importPath, _, err := appPackage(dir)
	if err != nil {
		return p, err
	}
	ldir := filepath.Join(dir, loaderDir)
	if err := os.MkdirAll(ldir, 0o755); err != nil {
		return p, err
	}
	defer os.RemoveAll(ldir)

	body := fmt.Sprintf(loaderTemplate, importPath)
	if err := os.WriteFile(filepath.Join(ldir, "main.go"), []byte(body), 0o644); err != nil {
		return p, err
	}

	cmd := exec.Command("go", "run", "./"+loaderDir)
	cmd.Dir = dir
	var stderr strings.Builder
	cmd.Stderr = &stderr
	out, err := cmd.Output()
	if err != nil {
		// The compiler's own message is the only thing a developer
		// sees when their app doesn't build — wrapping it in a
		// generic "loader failed" would send them hunting for a bug
		// in rastrillo instead of the app.
		return p, fmt.Errorf("loading the app's models failed — the app must compile:\n%s", stderr.String())
	}
	if err := json.Unmarshal(out, &p); err != nil {
		return p, fmt.Errorf("could not parse the loader's output: %w", err)
	}
	return p, nil
}

func migrationsDir(dir string) (string, error) {
	_, pkg, err := appPackage(dir)
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "internal", pkg, "migrations"), nil
}

func dirArg(args []string) string {
	for _, a := range args {
		if !strings.HasPrefix(a, "-") {
			return a
		}
	}
	return "."
}

func migrationCheck(args []string) error {
	dir := dirArg(args)
	p, err := loadPayload(dir)
	if err != nil {
		return err
	}
	if len(p.Changes) == 0 {
		fmt.Println("rastrillo migration check: models and migrations agree")
		return nil
	}
	var b strings.Builder
	b.WriteString("models and migrations disagree:\n")
	for _, c := range p.Changes {
		b.WriteString("  " + strings.TrimSpace(c.SQL) + "\n")
	}
	b.WriteString("\nrun: rastrillo migration generate")
	return errors.New(b.String())
}

func migrationGenerate(args []string) error {
	dir := dirArg(args)
	allowDestructive := false
	for _, a := range args {
		if a == "--allow-destructive" {
			allowDestructive = true
		}
	}
	p, err := loadPayload(dir)
	if err != nil {
		return err
	}
	if len(p.Changes) == 0 {
		fmt.Println("rastrillo migration generate: nothing to do")
		return nil
	}

	var destructive []string
	for _, c := range p.Changes {
		if c.Destructive {
			destructive = append(destructive, strings.TrimSpace(c.SQL))
		}
	}
	if len(destructive) > 0 && !allowDestructive {
		return fmt.Errorf(
			"this change drops data:\n  %s\n\n"+
				"Re-run with --allow-destructive if that is what you want.\n"+
				"If you meant to rename rather than drop, write it by hand instead:\n"+
				"  rastrillo migration new rename_something\n"+
				"  ALTER TABLE t RENAME COLUMN old TO new;",
			strings.Join(destructive, "\n  "))
	}

	mdir, err := migrationsDir(dir)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(mdir, 0o755); err != nil {
		return err
	}
	name, err := nextMigrationName(mdir, describe(p.Changes))
	if err != nil {
		return err
	}
	var body strings.Builder
	for _, c := range p.Changes {
		body.WriteString(strings.TrimSpace(c.SQL))
		body.WriteString("\n\n")
	}
	if err := os.WriteFile(filepath.Join(mdir, name), []byte(body.String()), 0o644); err != nil {
		return err
	}
	fmt.Printf("rastrillo migration generate: wrote %s\n", filepath.Join(mdir, name))

	// schema.sql must reflect the migration just written, so recompute
	// it with the new file in place. This is a second full `go run` of
	// the app module — go:embed captures the migrations directory at
	// compile time, so the first loader's build can't have seen a file
	// that didn't exist yet.
	p2, err := loadPayload(dir)
	if err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(mdir, "schema.sql"), []byte(p2.Schema), 0o644); err != nil {
		return err
	}
	fmt.Printf("rastrillo migration generate: refreshed %s\n", filepath.Join(mdir, "schema.sql"))
	return nil
}

// describe names a migration after what it does, so the filename is
// readable in a diff without opening it.
//
// It cannot simply grep for "ADD COLUMN": gormlite's AddColumn (like
// upstream GORM's) emits "ALTER TABLE ... ADD <col> <type>", never
// the word COLUMN, and DropColumn/DropIndex have no DDL keyword to
// grep for at all — SQLite cannot ALTER TABLE DROP COLUMN, so gormlite
// rebuilds the table (CREATE TABLE ...__temp, INSERT INTO, DROP TABLE,
// then ALTER TABLE ... RENAME TO) and the recorder captures every
// statement in that rebuild. The RENAME TO that ends a rebuild is
// checked first, ahead of CREATE TABLE, precisely because a rebuild's
// own synthetic CREATE TABLE ...__temp would otherwise win the naive
// first-match and mislabel a dropped column as a created table.
func describe(changes []migrate.Change) string {
	for _, c := range changes {
		if strings.Contains(strings.ToUpper(c.SQL), "RENAME TO") {
			return "drop_column_" + renamedTable(c.SQL)
		}
	}
	for _, c := range changes {
		u := strings.ToUpper(c.SQL)
		switch {
		case strings.HasPrefix(u, "CREATE TABLE"):
			return "create_" + tableIn(c.SQL)
		case strings.HasPrefix(u, "ALTER TABLE") && strings.Contains(u, "ADD"):
			return "alter_" + tableIn(c.SQL)
		case strings.HasPrefix(u, "DROP TABLE"):
			return "drop_" + tableIn(c.SQL)
		}
	}
	return "schema"
}

func tableIn(sqlText string) string {
	fields := strings.Fields(strings.ReplaceAll(sqlText, "`", " "))
	for i, f := range fields {
		if !strings.EqualFold(f, "TABLE") {
			continue
		}
		// gormlite's DropTable emits "DROP TABLE IF EXISTS <name>" —
		// skip the "IF [NOT] EXISTS" clause rather than returning "IF".
		j := i + 1
		for j < len(fields) && (strings.EqualFold(fields[j], "IF") ||
			strings.EqualFold(fields[j], "NOT") || strings.EqualFold(fields[j], "EXISTS")) {
			j++
		}
		if j < len(fields) {
			return strings.Trim(strings.ToLower(fields[j]), `"'();`)
		}
	}
	return "schema"
}

// renamedTable reads the destination name off an "... RENAME TO x"
// statement — the real table name once gormlite's rebuild finishes —
// rather than tableIn's "TABLE"-relative lookup, which on this
// statement shape would return the transient "...__temp" source name.
func renamedTable(sqlText string) string {
	fields := strings.Fields(strings.ReplaceAll(sqlText, "`", " "))
	for i, f := range fields {
		if strings.EqualFold(f, "TO") && i+1 < len(fields) {
			return strings.Trim(strings.ToLower(fields[i+1]), `"'();`)
		}
	}
	return tableIn(sqlText)
}

func nextMigrationName(mdir, label string) (string, error) {
	entries, err := os.ReadDir(mdir)
	if err != nil && !os.IsNotExist(err) {
		return "", err
	}
	n := 0
	for _, e := range entries {
		if len(e.Name()) < 4 {
			continue
		}
		var got int
		if _, err := fmt.Sscanf(e.Name()[:4], "%04d", &got); err == nil && got > n {
			n = got
		}
	}
	return fmt.Sprintf("%04d_%s.sql", n+1, label), nil
}
