package main

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// scaffoldWithReplace runs rastrillo new with args, points the app at
// this checkout, and tidies it, the scratch-module pattern
// TestScaffoldMigratesAndPassesCheck uses.
func scaffoldWithReplace(t *testing.T, name string, args ...string) string {
	t.Helper()
	root := repoRoot(t)
	if err := runNew(append(args, name)); err != nil {
		t.Fatalf("runNew: %v", err)
	}
	f, err := os.OpenFile(filepath.Join(name, "go.mod"), os.O_APPEND|os.O_WRONLY, 0o644)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := f.WriteString("\nreplace amadan.net/rastrillo/rastrillo => " + root + "\n"); err != nil {
		t.Fatal(err)
	}
	if err := f.Close(); err != nil {
		t.Fatal(err)
	}
	tidy := exec.Command("go", "mod", "tidy")
	tidy.Dir = name
	if out, err := tidy.CombinedOutput(); err != nil {
		t.Fatalf("go mod tidy:\n%s", out)
	}
	dir, err := filepath.Abs(name)
	if err != nil {
		t.Fatal(err)
	}
	return dir
}

func goTestIn(dir string, args ...string) (string, error) {
	cmd := exec.Command("go", append([]string{"test", "-count=1"}, args...)...)
	cmd.Dir = dir
	out, err := cmd.CombinedOutput()
	return string(out), err
}

// TestAnAppMissingTheShellFilesIsToldAndFixed pins the upgrade path for
// the two shell files. Upgrading the module adds them to the app's own
// vendoring test, and an app that has not got them fails it with the
// existing missing-file diagnostic (its test file is not regenerated by
// a module upgrade, so the doctor hint on the mismatch branch never
// shows); `rastrillo doctor --fix` writes them and the test passes; an
// app that deletes them on purpose and says so in vendoredIsMine passes
// too.
func TestAnAppMissingTheShellFilesIsToldAndFixed(t *testing.T) {
	if testing.Short() {
		t.Skip("scaffolds, tidies and tests a whole app")
	}
	setSandboxGoEnv(t)
	t.Chdir(t.TempDir())
	dir := scaffoldWithReplace(t, "upapp", "--shell=topbar")
	static := filepath.Join(dir, "internal", "upapp", "static")
	pin := filepath.Join(dir, "internal", "upapptest", "vendored_test.go")
	remove := func() {
		for _, n := range []string{"shell.js", "shell.css"} {
			if err := os.Remove(filepath.Join(static, n)); err != nil {
				t.Fatal(err)
			}
		}
	}
	run := func() (string, error) {
		return goTestIn(dir, "./internal/upapptest/", "-run", "TestVendoredAssetsMatchTheLibrary")
	}

	if out, err := run(); err != nil {
		t.Fatalf("a fresh scaffold fails its own vendoring test:\n%s", out)
	}
	remove()
	out, err := run()
	if err == nil || !strings.Contains(out, "read vendored shell.js") || !strings.Contains(out, "read vendored shell.css") {
		t.Fatalf("an app missing the shell files: err %v, want the missing-file diagnostic for both:\n%s", err, out)
	}
	if err := runDoctor([]string{"--fix", dir}); err != nil {
		t.Fatalf("doctor --fix: %v", err)
	}
	if out, err := run(); err != nil {
		t.Fatalf("after doctor --fix the vendoring test still fails:\n%s", out)
	}

	remove()
	src, err := os.ReadFile(pin)
	if err != nil {
		t.Fatal(err)
	}
	claimed := strings.Replace(string(src), "var vendoredIsMine = map[string]bool{", "var vendoredIsMine = map[string]bool{\n\t\"shell.js\": true,\n\t\"shell.css\": true,", 1)
	if claimed == string(src) {
		t.Fatal("could not find vendoredIsMine in the scaffolded pin")
	}
	if err := os.WriteFile(pin, []byte(claimed), 0o644); err != nil {
		t.Fatal(err)
	}
	if out, err := run(); err != nil {
		t.Fatalf("deleting the shell files and listing them in vendoredIsMine still fails:\n%s", out)
	}
}
