package main

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"amadan.net/rastrillo/rastrillo/ui"
)

// scaffoldWithReplace runs rastrillo new with args, points the app at
// this checkout, and tidies it, the scratch-module pattern
// TestScaffoldMigratesAndPassesCheck uses.
func scaffoldWithReplace(t *testing.T, name string, args ...string) string {
	t.Helper()
	root := repoRoot(t)
	if err := runNew(append(args, name)); err != nil {
		t.Fatalf("runNew: %v", err)
	}
	f, err := os.OpenFile(filepath.Join(name, "go.mod"), os.O_APPEND|os.O_WRONLY, 0o644)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := f.WriteString("\nreplace amadan.net/rastrillo/rastrillo => " + root + "\n"); err != nil {
		t.Fatal(err)
	}
	if err := f.Close(); err != nil {
		t.Fatal(err)
	}
	tidy := exec.Command("go", "mod", "tidy")
	tidy.Dir = name
	if out, err := tidy.CombinedOutput(); err != nil {
		t.Fatalf("go mod tidy:\n%s", out)
	}
	dir, err := filepath.Abs(name)
	if err != nil {
		t.Fatal(err)
	}
	return dir
}

func goTestIn(dir string, args ...string) (string, error) {
	cmd := exec.Command("go", append([]string{"test", "-count=1"}, args...)...)
	cmd.Dir = dir
	out, err := cmd.CombinedOutput()
	return string(out), err
}

// TestAnAppMissingTheShellFilesIsToldAndFixed pins the upgrade path for
// the two shell files. Upgrading the module adds them to the app's own
// vendoring test, and an app that has not got them fails it with the
// existing missing-file diagnostic (its test file is not regenerated by
// a module upgrade, so the doctor hint on the mismatch branch never
// shows); `rastrillo doctor --fix` writes them and the test passes; an
// app that deletes them on purpose and says so in vendoredIsMine passes
// too.
func TestAnAppMissingTheShellFilesIsToldAndFixed(t *testing.T) {
	if testing.Short() {
		t.Skip("scaffolds, tidies and tests a whole app")
	}
	setSandboxGoEnv(t)
	t.Chdir(t.TempDir())
	dir := scaffoldWithReplace(t, "upapp", "--shell=topbar")
	static := filepath.Join(dir, "internal", "upapp", "static")
	pin := filepath.Join(dir, "internal", "upapptest", "vendored_test.go")
	remove := func() {
		for _, n := range []string{"shell.js", "shell.css"} {
			if err := os.Remove(filepath.Join(static, n)); err != nil {
				t.Fatal(err)
			}
		}
	}
	run := func() (string, error) {
		return goTestIn(dir, "./internal/upapptest/", "-run", "TestVendoredAssetsMatchTheLibrary")
	}

	if out, err := run(); err != nil {
		t.Fatalf("a fresh scaffold fails its own vendoring test:\n%s", out)
	}
	remove()
	out, err := run()
	if err == nil || !strings.Contains(out, "read vendored shell.js") || !strings.Contains(out, "read vendored shell.css") {
		t.Fatalf("an app missing the shell files: err %v, want the missing-file diagnostic for both:\n%s", err, out)
	}
	if err := runDoctor([]string{"--fix", dir}); err != nil {
		t.Fatalf("doctor --fix: %v", err)
	}
	if out, err := run(); err != nil {
		t.Fatalf("after doctor --fix the vendoring test still fails:\n%s", out)
	}

	remove()
	src, err := os.ReadFile(pin)
	if err != nil {
		t.Fatal(err)
	}
	claimed := strings.Replace(string(src), "var vendoredIsMine = map[string]bool{", "var vendoredIsMine = map[string]bool{\n\t\"shell.js\": true,\n\t\"shell.css\": true,", 1)
	if claimed == string(src) {
		t.Fatal("could not find vendoredIsMine in the scaffolded pin")
	}
	if err := os.WriteFile(pin, []byte(claimed), 0o644); err != nil {
		t.Fatal(err)
	}
	if out, err := run(); err != nil {
		t.Fatalf("deleting the shell files and listing them in vendoredIsMine still fails:\n%s", out)
	}
}

// A sidebar or console app opens on a phone to its index, whose content
// is hidden there, so the scaffold writes an index with one section in
// its nav and the section page it opens, with its way back. The other
// shells keep today's one page.
func TestNewWritesAnIndexAndASectionForTheShellsThatHaveOne(t *testing.T) {
	t.Chdir(t.TempDir())
	for _, shell := range ui.LayoutNames() {
		name := "app" + shell
		if err := runNew([]string{"--shell=" + shell, name}); err != nil {
			t.Fatalf("%s: runNew: %v", shell, err)
		}
		dir := filepath.Join(name, "internal", name)
		index := readScaffold(t, dir, "templates", "index.html")
		app := readScaffold(t, dir, "app.go")
		handlers := readScaffold(t, dir, "handlers.go")
		render := readScaffold(t, dir, "render.go")
		overview, err := os.ReadFile(filepath.Join(dir, "templates", "overview.html"))
		if !twoPageShells[shell] {
			if err == nil || strings.Contains(app, "/overview") || index != indexTemplate {
				t.Errorf("%s: the one-page shells keep today's single page", shell)
			}
			continue
		}
		for _, c := range []struct{ file, got, want string }{
			{"index.html", index, `{{define "view"}}index{{end}}`},
			{"index.html", index, `<a id="nav-overview" href="/overview">` + scaffoldOverview + `</a>`},
			{"overview.html", string(overview), `{{define "up"}}/#nav-overview{{end}}`},
			{"overview.html", string(overview), `<a id="nav-overview" href="/overview" aria-current="page">` + scaffoldOverview + `</a>`},
			{"app.go", app, `r.Get("/overview", a.overview)`},
			{"handlers.go", handlers, `func (a *app) overview(w http.ResponseWriter, r *http.Request) {`},
			{"render.go", render, `[]string{"index", "overview", "errors"}`},
		} {
			if !strings.Contains(c.got, c.want) {
				t.Errorf("%s: %s lacks %q", shell, c.file, c.want)
			}
		}
		if err != nil {
			t.Errorf("%s: no overview.html: %v", shell, err)
		}
	}
}

// The two-page scaffold builds, vets under the browser tag, and passes
// its own tests, the new overview test among them.
func TestAScaffoldedSidebarAppPassesItsOwnTests(t *testing.T) {
	if testing.Short() {
		t.Skip("scaffolds, tidies and tests a whole app")
	}
	setSandboxGoEnv(t)
	t.Chdir(t.TempDir())
	dir := scaffoldWithReplace(t, "phoneapp", "--shell=sidebar")
	out, err := goTestIn(dir, "-v", "./...")
	if err != nil {
		t.Fatalf("the scaffolded sidebar app's tests fail:\n%s", out)
	}
	if !strings.Contains(out, "--- PASS: TestOverviewRenders") {
		t.Errorf("the scaffolded suite did not run TestOverviewRenders:\n%s", out)
	}
	vet := exec.Command("go", "vet", "-tags", "browser", "./...")
	vet.Dir = dir
	if b, err := vet.CombinedOutput(); err != nil {
		t.Fatalf("go vet -tags browser:\n%s", b)
	}
}
