package generate

import (
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"amadan.net/rastrillo/rastrillo"
)

// newActionsAppRoot builds an app root with just enough of a go.mod for
// actionsModulePath to resolve a module path — EmitActions needs one to
// build the store package's import path, unlike EmitStore/EmitTemplates
// which never emit Go import statements.
func newActionsAppRoot(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "go.mod"), []byte("module scratch\n\ngo 1.25.0\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	return dir
}

// goldenIndexGETGo is EmitActions' output for the fixture's index.GET
// (List): Search + one Filter (Title) declared, so both the search box
// and the filter's query param round-trip through the store's Params
// structs; Rows come from List.Columns[0]/[1] (Title/Price, Price
// formatted through form.FormatCents); pagination has no gap-collapsing
// (every page number renders — a v1 simplification, see the report).
const goldenIndexGETGo = `// Code generated by rastrillo generate. DO NOT EDIT.

package act_admin_notes_index_get

import (
	"fmt"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"amadan.net/rastrillo/rastrillo"
	"amadan.net/rastrillo/rastrillo/form"
	"amadan.net/rastrillo/rastrillo/view"
	notesstore "scratch/gen/store/notes"
)

// Handle is GET /admin/notes.
func Handle(ctx *rastrillo.Ctx, w http.ResponseWriter, r *http.Request) {
	search := strings.TrimSpace(r.URL.Query().Get("q"))
	filterTitle := r.URL.Query().Get("title")

	page := 1
	if v := r.URL.Query().Get("page"); v != "" {
		if n, err := strconv.Atoi(v); err == nil && n > 0 {
			page = n
		}
	}
	const pageSize = 10
	offset := (page - 1) * pageSize

	var carry [][2]string
	if filterTitle != "" {
		carry = append(carry, [2]string{"title", filterTitle})
	}

	store := notesstore.New(ctx.DB)
	total, err := store.CountNotes(r.Context(), notesstore.CountNotesParams{
		Search:      search,
		FilterTitle: filterTitle,
	})
	if err != nil {
		view.Fail(ctx, w, r, "notes: counting notes", err)
		return
	}
	rows, err := store.ListNotes(r.Context(), notesstore.ListNotesParams{
		Search:      search,
		FilterTitle: filterTitle,
		PageOffset:  int64(offset),
		PageLimit:   pageSize,
	})
	if err != nil {
		view.Fail(ctx, w, r, "notes: loading notes", err)
		return
	}

	items := make([]listRow, 0, len(rows))
	for _, n := range rows {
		items = append(items, listRow{
			Href: fmt.Sprintf("/admin/notes/%d", n.ID),
			Main: n.Title,
			Sub:  form.FormatCents(n.Price),
		})
	}

	totalPages := (int(total) + pageSize - 1) / pageSize
	show := int(total) > pageSize
	var pageItems []listPageItem
	if show {
		prev := listPageItem{Label: "Previous", Disabled: true}
		if page > 1 {
			prev = listPageItem{Label: "Previous", Href: href(search, carry, page-1)}
		}
		pageItems = append(pageItems, prev)
		for n := 1; n <= totalPages; n++ {
			if n == page {
				pageItems = append(pageItems, listPageItem{Label: strconv.Itoa(n), Current: true})
			} else {
				pageItems = append(pageItems, listPageItem{Label: strconv.Itoa(n), Href: href(search, carry, n)})
			}
		}
		next := listPageItem{Label: "Next", Disabled: true}
		if page < totalPages {
			next = listPageItem{Label: "Next", Href: href(search, carry, page+1)}
		}
		pageItems = append(pageItems, next)
	}

	view.Render(ctx, w, "notes/list", http.StatusOK, listView{
		Empty:      total == 0,
		Query:      search,
		Carry:      carry,
		Rows:       items,
		Pagination: listPagination{Show: show, Items: pageItems},
	})
}

// href builds one list/pagination link, preserving the current search
// and filter values and setting page.
func href(search string, carry [][2]string, page int) string {
	var params []string
	if search != "" {
		params = append(params, "q="+url.QueryEscape(search))
	}
	for _, kv := range carry {
		params = append(params, kv[0]+"="+url.QueryEscape(kv[1]))
	}
	params = append(params, "page="+strconv.Itoa(page))
	return "/admin/notes" + "?" + strings.Join(params, "&")
}

type listView struct {
	Empty      bool
	Query      string
	Carry      [][2]string
	Rows       []listRow
	Pagination listPagination
}

type listRow struct {
	Href string
	Main string
	Sub  string
}

type listPagination struct {
	Show  bool
	Items []listPageItem
}

type listPageItem struct {
	Label    string
	Href     string
	Current  bool
	Disabled bool
	Gap      bool
}
`

// goldenEditBasicsPOSTGo is EmitActions' output for the fixture's
// [id]/edit-basics.POST: Form.Basics is Title (Text) and Body
// (Textarea) — no Money field in this group at all, so no validation
// branch is emitted (generation time already knows no parse here can
// fail; see the package doc). The existence Get is still present
// (Get-or-404 before ever attempting the UPDATE), its result just
// discarded.
const goldenEditBasicsPOSTGo = `// Code generated by rastrillo generate. DO NOT EDIT.

package act_admin_notes_id_edit_basics_post

import (
	"database/sql"
	"errors"
	"fmt"
	"net/http"
	"time"

	"amadan.net/rastrillo/rastrillo"
	"amadan.net/rastrillo/rastrillo/form"
	"amadan.net/rastrillo/rastrillo/view"
	notesstore "scratch/gen/store/notes"
)

// Handle is POST /admin/notes/{id}/edit-basics.
func Handle(ctx *rastrillo.Ctx, w http.ResponseWriter, r *http.Request) {
	r.Body = http.MaxBytesReader(w, r.Body, 1<<20)
	if err := r.ParseForm(); err != nil {
		http.Error(w, "Bad request.", http.StatusBadRequest)
		return
	}
	id, ok := view.ParseID(r)
	if !ok {
		view.NotFound(ctx, w, r)
		return
	}
	store := notesstore.New(ctx.DB)
	_, err := store.GetNote(r.Context(), id)
	if errors.Is(err, sql.ErrNoRows) {
		view.NotFound(ctx, w, r)
		return
	}
	if err != nil {
		view.Fail(ctx, w, r, "notes: loading notes", err)
		return
	}

	p := form.Parse(r,
		form.Field{Name: "Title"},
		form.Field{Name: "Body", Kind: form.Textarea},
	)

	now := time.Now().UTC().Format(time.RFC3339)
	if err := store.UpdateNoteBasics(r.Context(), notesstore.UpdateNoteBasicsParams{
		Title: p.String("Title"),
		Body:  p.String("Body"),
		Now:   now,
		ID:    id,
	}); err != nil {
		view.Fail(ctx, w, r, "notes: updating notes", err)
		return
	}
	http.Redirect(w, r, fmt.Sprintf("/admin/notes/%d", id), http.StatusSeeOther)
}
`

// goldenEditGETGo is EmitActions' output for the fixture's
// [id]/edit.GET: this is the golden that pins the money patch (see the
// report) — Price is a Money column, and edit.GET's Fields must seed
// it through form.FormatCentsPlain ("1.00"), NOT form.FormatCents
// ("$1.00"). An earlier draft used formatCents here, which meant
// resubmitting an edit form with an unchanged Price always 400ed
// (form.ParseCents rejects the leading "$").
const goldenEditGETGo = `// Code generated by rastrillo generate. DO NOT EDIT.

package act_admin_notes_id_edit_get

import (
	"database/sql"
	"errors"
	"fmt"
	"net/http"

	"amadan.net/rastrillo/rastrillo"
	"amadan.net/rastrillo/rastrillo/form"
	"amadan.net/rastrillo/rastrillo/view"
	notesstore "scratch/gen/store/notes"
)

// Handle is GET /admin/notes/{id}/edit.
func Handle(ctx *rastrillo.Ctx, w http.ResponseWriter, r *http.Request) {
	id, ok := view.ParseID(r)
	if !ok {
		view.NotFound(ctx, w, r)
		return
	}
	store := notesstore.New(ctx.DB)
	n, err := store.GetNote(r.Context(), id)
	if errors.Is(err, sql.ErrNoRows) {
		view.NotFound(ctx, w, r)
		return
	}
	if err != nil {
		view.Fail(ctx, w, r, "notes: loading notes", err)
		return
	}

	view.Render(ctx, w, "notes/form", http.StatusOK, formView{
		IsNew: false,
		Fields: map[string]string{
			"Title": n.Title,
			"Price": form.FormatCentsPlain(n.Price),
			"Body":  n.Body,
		},
		BasicsAction:   fmt.Sprintf("/admin/notes/%d/edit-basics", id),
		AdvancedAction: fmt.Sprintf("/admin/notes/%d/edit-advanced", id),
	})
}

type formView struct {
	IsNew          bool
	Fields         map[string]string
	Errors         map[string]string
	BasicsAction   string
	AdvancedAction string
}
`

// goldenEditAdvancedPOSTGo is EmitActions' output for the fixture's
// [id]/edit-advanced.POST: Form.Advanced is just Price (Money), so
// groupHasMoney is true and the validation-failure re-render branch is
// emitted. Two things the money patch touches are both visible here:
// the base "fields" map (seeded with the OTHER group's — Basics' —
// current values, since only Price belongs to this group) uses
// form.FormatCentsPlain for Price exactly like edit.GET's Fields does, and
// the just-submitted raw Price text (fields["Price"] = vPriceRaw)
// still overrides it afterward, untouched — a typo stays exactly as
// typed for correction, the same as before this patch.
const goldenEditAdvancedPOSTGo = `// Code generated by rastrillo generate. DO NOT EDIT.

package act_admin_notes_id_edit_advanced_post

import (
	"database/sql"
	"errors"
	"fmt"
	"net/http"
	"time"

	"amadan.net/rastrillo/rastrillo"
	"amadan.net/rastrillo/rastrillo/form"
	"amadan.net/rastrillo/rastrillo/view"
	notesstore "scratch/gen/store/notes"
)

// Handle is POST /admin/notes/{id}/edit-advanced.
func Handle(ctx *rastrillo.Ctx, w http.ResponseWriter, r *http.Request) {
	r.Body = http.MaxBytesReader(w, r.Body, 1<<20)
	if err := r.ParseForm(); err != nil {
		http.Error(w, "Bad request.", http.StatusBadRequest)
		return
	}
	id, ok := view.ParseID(r)
	if !ok {
		view.NotFound(ctx, w, r)
		return
	}
	store := notesstore.New(ctx.DB)
	n, err := store.GetNote(r.Context(), id)
	if errors.Is(err, sql.ErrNoRows) {
		view.NotFound(ctx, w, r)
		return
	}
	if err != nil {
		view.Fail(ctx, w, r, "notes: loading notes", err)
		return
	}

	p := form.Parse(r,
		form.Field{Name: "Price", Kind: form.Money},
	)

	if !p.OK() {
		fields := map[string]string{
			"Title": n.Title,
			"Price": form.FormatCentsPlain(n.Price),
			"Body":  n.Body,
		}
		for k, v := range p.Echo() {
			fields[k] = v
		}
		view.Render(ctx, w, "notes/form", http.StatusBadRequest, formView{
			IsNew:          false,
			Fields:         fields,
			Errors:         p.Errors(),
			BasicsAction:   fmt.Sprintf("/admin/notes/%d/edit-basics", id),
			AdvancedAction: fmt.Sprintf("/admin/notes/%d/edit-advanced", id),
		})
		return
	}

	now := time.Now().UTC().Format(time.RFC3339)
	if err := store.UpdateNoteAdvanced(r.Context(), notesstore.UpdateNoteAdvancedParams{
		Price: p.Cents("Price"),
		Now:   now,
		ID:    id,
	}); err != nil {
		view.Fail(ctx, w, r, "notes: updating notes", err)
		return
	}
	http.Redirect(w, r, fmt.Sprintf("/admin/notes/%d", id), http.StatusSeeOther)
}

type formView struct {
	IsNew          bool
	Fields         map[string]string
	Errors         map[string]string
	BasicsAction   string
	AdvancedAction string
}
`

// goldenFilteredIndexGETGo is EmitActions' output for
// filteredFixtureResource()'s index.GET (List): Status is declared BOTH
// as a bare List.Filter and as a List.Filters entry with Values
// draft/live — filterFields dedupes the two to one filterVar, but
// because it IS also declared via Filters, its raw query read is
// replaced with normalizeStatus(...) (unknown/absent -> "", never a raw
// passthrough) and Handle builds a filterView the render call's Filter
// field carries: SummaryKey/AriaField/each Item's LabelKey are T KEYS,
// never resolved strings (see the package doc's "labels resolve at
// RENDER time" note) — resource.events.filter.status.<value> per
// declared value, resource.events.field.status for AriaField, ui.all
// for the "All" item and the applied-value summary when none is
// applied. Every Href goes through filterStatusHref, which carries the
// current search and this ONE filter value, never page.
const goldenFilteredIndexGETGo = `// Code generated by rastrillo generate. DO NOT EDIT.

package act_admin_events_index_get

import (
	"fmt"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"amadan.net/rastrillo/rastrillo"
	"amadan.net/rastrillo/rastrillo/view"
	eventsstore "scratch/gen/store/events"
)

// Handle is GET /admin/events.
func Handle(ctx *rastrillo.Ctx, w http.ResponseWriter, r *http.Request) {
	search := strings.TrimSpace(r.URL.Query().Get("q"))
	filterStatus := normalizeStatus(r.URL.Query().Get("status"))

	page := 1
	if v := r.URL.Query().Get("page"); v != "" {
		if n, err := strconv.Atoi(v); err == nil && n > 0 {
			page = n
		}
	}
	const pageSize = 10
	offset := (page - 1) * pageSize

	var carry [][2]string
	if filterStatus != "" {
		carry = append(carry, [2]string{"status", filterStatus})
	}

	store := eventsstore.New(ctx.DB)
	total, err := store.CountEvents(r.Context(), eventsstore.CountEventsParams{
		Search:       search,
		FilterStatus: filterStatus,
	})
	if err != nil {
		view.Fail(ctx, w, r, "events: counting events", err)
		return
	}
	rows, err := store.ListEvents(r.Context(), eventsstore.ListEventsParams{
		Search:       search,
		FilterStatus: filterStatus,
		PageOffset:   int64(offset),
		PageLimit:    pageSize,
	})
	if err != nil {
		view.Fail(ctx, w, r, "events: loading events", err)
		return
	}

	items := make([]listRow, 0, len(rows))
	for _, n := range rows {
		items = append(items, listRow{
			Href: fmt.Sprintf("/admin/events/%d", n.ID),
			Main: n.Title,
			Sub:  n.Status,
		})
	}

	totalPages := (int(total) + pageSize - 1) / pageSize
	show := int(total) > pageSize
	var pageItems []listPageItem
	if show {
		prev := listPageItem{Label: "Previous", Disabled: true}
		if page > 1 {
			prev = listPageItem{Label: "Previous", Href: href(search, carry, page-1)}
		}
		pageItems = append(pageItems, prev)
		for n := 1; n <= totalPages; n++ {
			if n == page {
				pageItems = append(pageItems, listPageItem{Label: strconv.Itoa(n), Current: true})
			} else {
				pageItems = append(pageItems, listPageItem{Label: strconv.Itoa(n), Href: href(search, carry, n)})
			}
		}
		next := listPageItem{Label: "Next", Disabled: true}
		if page < totalPages {
			next = listPageItem{Label: "Next", Href: href(search, carry, page+1)}
		}
		pageItems = append(pageItems, next)
	}

	filter := filterView{
		SummaryKey: filterStatusLabelKey(filterStatus),
		AriaField:  "resource.events.field.status",
		Items: []filterItem{
			{Href: filterStatusHref(search, ""), LabelKey: filterStatusLabelKey(""), Current: filterStatus == ""},
			{Href: filterStatusHref(search, "draft"), LabelKey: filterStatusLabelKey("draft"), Current: filterStatus == "draft"},
			{Href: filterStatusHref(search, "live"), LabelKey: filterStatusLabelKey("live"), Current: filterStatus == "live"},
		},
	}

	view.Render(ctx, w, "events/list", http.StatusOK, listView{
		Empty:      total == 0,
		Query:      search,
		Carry:      carry,
		Filter:     filter,
		Rows:       items,
		Pagination: listPagination{Show: show, Items: pageItems},
	})
}

// href builds one list/pagination link, preserving the current search
// and filter values and setting page.
func href(search string, carry [][2]string, page int) string {
	var params []string
	if search != "" {
		params = append(params, "q="+url.QueryEscape(search))
	}
	for _, kv := range carry {
		params = append(params, kv[0]+"="+url.QueryEscape(kv[1]))
	}
	params = append(params, "page="+strconv.Itoa(page))
	return "/admin/events" + "?" + strings.Join(params, "&")
}

// normalizeStatus maps a raw query value onto Status's declared filter values:
// anything else — an empty string, a stale bookmark, a hand-edited URL —
// normalizes to "" (all), never a 400.
func normalizeStatus(raw string) string {
	switch raw {
	case "draft", "live":
		return raw
	}
	return ""
}

// filterStatusLabelKey resolves a normalized Status value ("" or a declared
// value) to its catalog key; T renders it at request time, never here.
func filterStatusLabelKey(v string) string {
	if v == "" {
		return "ui.all"
	}
	return "resource.events.filter.status." + v
}

// filterStatusHref builds one Status dropdown item's link: the current search
// plus this filter value (never page — changing a filter starts at page
// 1 by construction), value == "" for the "All" item.
func filterStatusHref(search, value string) string {
	var params []string
	if search != "" {
		params = append(params, "q="+url.QueryEscape(search))
	}
	if value != "" {
		params = append(params, "status="+url.QueryEscape(value))
	}
	if len(params) == 0 {
		return "/admin/events"
	}
	return "/admin/events" + "?" + strings.Join(params, "&")
}

type listView struct {
	Empty      bool
	Query      string
	Carry      [][2]string
	Filter     filterView
	Rows       []listRow
	Pagination listPagination
}

type filterView struct {
	SummaryKey string
	AriaField  string
	Items      []filterItem
}

type filterItem struct {
	Href     string
	LabelKey string
	Current  bool
}

type listRow struct {
	Href string
	Main string
	Sub  string
}

type listPagination struct {
	Show  bool
	Items []listPageItem
}

type listPageItem struct {
	Label    string
	Href     string
	Current  bool
	Disabled bool
	Gap      bool
}
`

// TestEmitActionsFilteredIndexGETGolden pins EmitActions' index.GET
// output for filteredFixtureResource() (Status: bare List.Filter AND a
// List.Filters entry with Values draft/live) against
// goldenFilteredIndexGETGo — the Filters-declared counterpart to
// TestEmitActionsGoldenFiles' goldenIndexGETGo, which stays pinned
// against fixtureResource() (bare List.Filter only, no List.Filters)
// completely unchanged by this task — that is this task's byte-identical
// regression gate for a no-Filters resource, already enforced by the
// existing (unmodified) TestEmitActionsGoldenFiles and
// TestActionIndexGETCountCallShape.
func TestEmitActionsFilteredIndexGETGolden(t *testing.T) {
	appRoot := newActionsAppRoot(t)
	genDir := t.TempDir()
	r := filteredFixtureResource()

	if _, _, err := EmitActions(appRoot, genDir, r); err != nil {
		t.Fatalf("EmitActions: %v", err)
	}

	path := filepath.Join(genDir, "actions", "admin", "events", "index_get", "index.GET.go")
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	if string(got) != goldenFilteredIndexGETGo {
		t.Errorf("%s:\ngot:\n%s\nwant:\n%s", path, got, goldenFilteredIndexGETGo)
	}
}

// goldenFilteredIndexPOSTGo is EmitActions' output for
// filteredFixtureResource()'s index.POST (create): Title is Required
// (Text, so the check is against the already-trimmed vTitle), Status is
// not — exactly one errs check is emitted, pinning the shape parseField
// generates for a Required Text field with no Money field anywhere in
// the group (contrast goldenEditAdvancedPOSTGo's Money-only check).
const goldenFilteredIndexPOSTGo = `// Code generated by rastrillo generate. DO NOT EDIT.

package act_admin_events_index_post

import (
	"fmt"
	"net/http"
	"time"

	"amadan.net/rastrillo/rastrillo"
	"amadan.net/rastrillo/rastrillo/form"
	"amadan.net/rastrillo/rastrillo/view"
	eventsstore "scratch/gen/store/events"
)

// Handle is POST /admin/events.
func Handle(ctx *rastrillo.Ctx, w http.ResponseWriter, r *http.Request) {
	r.Body = http.MaxBytesReader(w, r.Body, 1<<20)
	if err := r.ParseForm(); err != nil {
		http.Error(w, "Bad request.", http.StatusBadRequest)
		return
	}

	p := form.Parse(r,
		form.Field{Name: "Title", Required: true},
		form.Field{Name: "Status"},
	)
	if !p.OK() {
		view.Render(ctx, w, "events/form", http.StatusBadRequest, formView{
			IsNew:  true,
			Fields: p.Echo(),
			Errors: p.Errors(),
		})
		return
	}

	now := time.Now().UTC().Format(time.RFC3339)
	store := eventsstore.New(ctx.DB)
	id, err := store.CreateEvent(r.Context(), eventsstore.CreateEventParams{
		Title:  p.String("Title"),
		Status: p.String("Status"),
		Now:    now,
	})
	if err != nil {
		view.Fail(ctx, w, r, "events: creating events", err)
		return
	}
	http.Redirect(w, r, fmt.Sprintf("/admin/events/%d", id), http.StatusSeeOther)
}

type formView struct {
	IsNew          bool
	Fields         map[string]string
	Errors         map[string]string
	BasicsAction   string
	AdvancedAction string
}
`

// TestEmitActionsFilteredIndexPOSTGolden pins EmitActions' index.POST
// output for filteredFixtureResource() (Title: Required) against
// goldenFilteredIndexPOSTGo. fixtureResource()'s own index.POST has no
// golden test today (no Required/Money-parse-failure shape distinct
// enough to need one before this task), so there is no separate
// no-Required regression golden to keep pinned here — TestEmitActionsCompile
// still proves fixtureResource()'s emitted create action compiles.
func TestEmitActionsFilteredIndexPOSTGolden(t *testing.T) {
	appRoot := newActionsAppRoot(t)
	genDir := t.TempDir()
	r := filteredFixtureResource()

	if _, _, err := EmitActions(appRoot, genDir, r); err != nil {
		t.Fatalf("EmitActions: %v", err)
	}

	path := filepath.Join(genDir, "actions", "admin", "events", "index_post", "index.POST.go")
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	if string(got) != goldenFilteredIndexPOSTGo {
		t.Errorf("%s:\ngot:\n%s\nwant:\n%s", path, got, goldenFilteredIndexPOSTGo)
	}
}

// goldenFilteredEditBasicsPOSTGo is EmitActions' output for
// filteredFixtureResource()'s [id]/edit-basics.POST: the same Required
// Text-only shape as goldenFilteredIndexPOSTGo, but on the Get-then-
// validate-then-Update path — pins that a Required field (with no Money
// field in its group) now DOES get the `n, err :=` Get (its result feeds
// the 400 re-render's Fields) and the validation branch, where before
// this task an all-Text group with no Money field had neither (see
// goldenEditBasicsPOSTGo, still pinned unchanged for fixtureResource()'s
// own Title/Body group, which declares no Required field).
const goldenFilteredEditBasicsPOSTGo = `// Code generated by rastrillo generate. DO NOT EDIT.

package act_admin_events_id_edit_basics_post

import (
	"database/sql"
	"errors"
	"fmt"
	"net/http"
	"time"

	"amadan.net/rastrillo/rastrillo"
	"amadan.net/rastrillo/rastrillo/form"
	"amadan.net/rastrillo/rastrillo/view"
	eventsstore "scratch/gen/store/events"
)

// Handle is POST /admin/events/{id}/edit-basics.
func Handle(ctx *rastrillo.Ctx, w http.ResponseWriter, r *http.Request) {
	r.Body = http.MaxBytesReader(w, r.Body, 1<<20)
	if err := r.ParseForm(); err != nil {
		http.Error(w, "Bad request.", http.StatusBadRequest)
		return
	}
	id, ok := view.ParseID(r)
	if !ok {
		view.NotFound(ctx, w, r)
		return
	}
	store := eventsstore.New(ctx.DB)
	n, err := store.GetEvent(r.Context(), id)
	if errors.Is(err, sql.ErrNoRows) {
		view.NotFound(ctx, w, r)
		return
	}
	if err != nil {
		view.Fail(ctx, w, r, "events: loading events", err)
		return
	}

	p := form.Parse(r,
		form.Field{Name: "Title", Required: true},
		form.Field{Name: "Status"},
	)

	if !p.OK() {
		fields := map[string]string{
			"Title":  n.Title,
			"Status": n.Status,
		}
		for k, v := range p.Echo() {
			fields[k] = v
		}
		view.Render(ctx, w, "events/form", http.StatusBadRequest, formView{
			IsNew:        false,
			Fields:       fields,
			Errors:       p.Errors(),
			BasicsAction: fmt.Sprintf("/admin/events/%d/edit-basics", id),
		})
		return
	}

	now := time.Now().UTC().Format(time.RFC3339)
	if err := store.UpdateEventBasics(r.Context(), eventsstore.UpdateEventBasicsParams{
		Title:  p.String("Title"),
		Status: p.String("Status"),
		Now:    now,
		ID:     id,
	}); err != nil {
		view.Fail(ctx, w, r, "events: updating events", err)
		return
	}
	http.Redirect(w, r, fmt.Sprintf("/admin/events/%d", id), http.StatusSeeOther)
}

type formView struct {
	IsNew          bool
	Fields         map[string]string
	Errors         map[string]string
	BasicsAction   string
	AdvancedAction string
}
`

// TestEmitActionsFilteredEditBasicsPOSTGolden pins EmitActions'
// edit-basics.POST output for filteredFixtureResource() against
// goldenFilteredEditBasicsPOSTGo — the Required counterpart to
// TestEmitActionsGoldenFiles' goldenEditBasicsPOSTGo, which stays pinned
// against fixtureResource() (no Required field in its Basics group)
// completely unchanged by this task: that is this task's byte-identical
// regression gate for a resource with no Required fields.
func TestEmitActionsFilteredEditBasicsPOSTGolden(t *testing.T) {
	appRoot := newActionsAppRoot(t)
	genDir := t.TempDir()
	r := filteredFixtureResource()

	if _, _, err := EmitActions(appRoot, genDir, r); err != nil {
		t.Fatalf("EmitActions: %v", err)
	}

	path := filepath.Join(genDir, "actions", "admin", "events", "id", "edit_basics_post", "edit-basics.POST.go")
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	if string(got) != goldenFilteredEditBasicsPOSTGo {
		t.Errorf("%s:\ngot:\n%s\nwant:\n%s", path, got, goldenFilteredEditBasicsPOSTGo)
	}
}

// goldenScopedIndexGETGo / goldenScopedIndexPOSTGo /
// goldenScopedDeletePOSTGo pin the scope = "user" action contract for
// scopedFixtureResource() (store_test.go): every scoped Handle resolves
// sessions.Current and answers 403 signed out; List/Count bind
// Owner: sess.Subject; Create stamps the owner; and the delete flow's
// Get and Delete both go through the two-field Params struct whose
// id-AND-owner WHERE makes someone else's row a 404. The unscoped
// goldens above are untouched by Scope's existence — that is the other
// half of the contract.
const goldenScopedIndexGETGo = `// Code generated by rastrillo generate. DO NOT EDIT.

package act_bookmarks_index_get

import (
	"fmt"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"amadan.net/rastrillo/rastrillo"
	"amadan.net/rastrillo/rastrillo/sessions"
	"amadan.net/rastrillo/rastrillo/view"
	bookmarksstore "scratch/gen/store/bookmarks"
)

// Handle is GET /bookmarks.
func Handle(ctx *rastrillo.Ctx, w http.ResponseWriter, r *http.Request) {
	sess, ok := sessions.Current(r)
	if !ok {
		view.Forbidden(ctx, w, r)
		return
	}
	search := strings.TrimSpace(r.URL.Query().Get("q"))

	page := 1
	if v := r.URL.Query().Get("page"); v != "" {
		if n, err := strconv.Atoi(v); err == nil && n > 0 {
			page = n
		}
	}
	const pageSize = 10
	offset := (page - 1) * pageSize

	var carry [][2]string

	store := bookmarksstore.New(ctx.DB)
	total, err := store.CountBookmarks(r.Context(), bookmarksstore.CountBookmarksParams{
		Owner:  sess.Subject,
		Search: search,
	})
	if err != nil {
		view.Fail(ctx, w, r, "bookmarks: counting bookmarks", err)
		return
	}
	rows, err := store.ListBookmarks(r.Context(), bookmarksstore.ListBookmarksParams{
		Owner:      sess.Subject,
		Search:     search,
		PageOffset: int64(offset),
		PageLimit:  pageSize,
	})
	if err != nil {
		view.Fail(ctx, w, r, "bookmarks: loading bookmarks", err)
		return
	}

	items := make([]listRow, 0, len(rows))
	for _, n := range rows {
		items = append(items, listRow{
			Href: fmt.Sprintf("/bookmarks/%d", n.ID),
			Main: n.Title,
			Sub:  n.Link,
		})
	}

	totalPages := (int(total) + pageSize - 1) / pageSize
	show := int(total) > pageSize
	var pageItems []listPageItem
	if show {
		prev := listPageItem{Label: "Previous", Disabled: true}
		if page > 1 {
			prev = listPageItem{Label: "Previous", Href: href(search, carry, page-1)}
		}
		pageItems = append(pageItems, prev)
		for n := 1; n <= totalPages; n++ {
			if n == page {
				pageItems = append(pageItems, listPageItem{Label: strconv.Itoa(n), Current: true})
			} else {
				pageItems = append(pageItems, listPageItem{Label: strconv.Itoa(n), Href: href(search, carry, n)})
			}
		}
		next := listPageItem{Label: "Next", Disabled: true}
		if page < totalPages {
			next = listPageItem{Label: "Next", Href: href(search, carry, page+1)}
		}
		pageItems = append(pageItems, next)
	}

	view.Render(ctx, w, "bookmarks/list", http.StatusOK, listView{
		Empty:      total == 0,
		Query:      search,
		Carry:      carry,
		Rows:       items,
		Pagination: listPagination{Show: show, Items: pageItems},
	})
}

// href builds one list/pagination link, preserving the current search
// and filter values and setting page.
func href(search string, carry [][2]string, page int) string {
	var params []string
	if search != "" {
		params = append(params, "q="+url.QueryEscape(search))
	}
	for _, kv := range carry {
		params = append(params, kv[0]+"="+url.QueryEscape(kv[1]))
	}
	params = append(params, "page="+strconv.Itoa(page))
	return "/bookmarks" + "?" + strings.Join(params, "&")
}

type listView struct {
	Empty      bool
	Query      string
	Carry      [][2]string
	Rows       []listRow
	Pagination listPagination
}

type listRow struct {
	Href string
	Main string
	Sub  string
}

type listPagination struct {
	Show  bool
	Items []listPageItem
}

type listPageItem struct {
	Label    string
	Href     string
	Current  bool
	Disabled bool
	Gap      bool
}
`

const goldenScopedIndexPOSTGo = `// Code generated by rastrillo generate. DO NOT EDIT.

package act_bookmarks_index_post

import (
	"fmt"
	"net/http"
	"time"

	"amadan.net/rastrillo/rastrillo"
	"amadan.net/rastrillo/rastrillo/form"
	"amadan.net/rastrillo/rastrillo/sessions"
	"amadan.net/rastrillo/rastrillo/view"
	bookmarksstore "scratch/gen/store/bookmarks"
)

// Handle is POST /bookmarks.
func Handle(ctx *rastrillo.Ctx, w http.ResponseWriter, r *http.Request) {
	r.Body = http.MaxBytesReader(w, r.Body, 1<<20)
	if err := r.ParseForm(); err != nil {
		http.Error(w, "Bad request.", http.StatusBadRequest)
		return
	}

	sess, ok := sessions.Current(r)
	if !ok {
		view.Forbidden(ctx, w, r)
		return
	}
	p := form.Parse(r,
		form.Field{Name: "Title", Required: true},
		form.Field{Name: "Link"},
		form.Field{Name: "Notes", Kind: form.Textarea},
	)
	if !p.OK() {
		view.Render(ctx, w, "bookmarks/form", http.StatusBadRequest, formView{
			IsNew:  true,
			Fields: p.Echo(),
			Errors: p.Errors(),
		})
		return
	}

	now := time.Now().UTC().Format(time.RFC3339)
	store := bookmarksstore.New(ctx.DB)
	id, err := store.CreateBookmark(r.Context(), bookmarksstore.CreateBookmarkParams{
		Owner: sess.Subject,
		Title: p.String("Title"),
		Link:  p.String("Link"),
		Notes: p.String("Notes"),
		Now:   now,
	})
	if err != nil {
		view.Fail(ctx, w, r, "bookmarks: creating bookmarks", err)
		return
	}
	http.Redirect(w, r, fmt.Sprintf("/bookmarks/%d", id), http.StatusSeeOther)
}

type formView struct {
	IsNew          bool
	Fields         map[string]string
	Errors         map[string]string
	BasicsAction   string
	AdvancedAction string
}
`

const goldenScopedDeletePOSTGo = `// Code generated by rastrillo generate. DO NOT EDIT.

package act_bookmarks_id_delete_post

import (
	"database/sql"
	"errors"
	"net/http"

	"amadan.net/rastrillo/rastrillo"
	"amadan.net/rastrillo/rastrillo/sessions"
	"amadan.net/rastrillo/rastrillo/view"
	bookmarksstore "scratch/gen/store/bookmarks"
)

// Handle is POST /bookmarks/{id}/delete.
func Handle(ctx *rastrillo.Ctx, w http.ResponseWriter, r *http.Request) {
	id, ok := view.ParseID(r)
	if !ok {
		view.NotFound(ctx, w, r)
		return
	}
	sess, ok := sessions.Current(r)
	if !ok {
		view.Forbidden(ctx, w, r)
		return
	}
	store := bookmarksstore.New(ctx.DB)
	if _, err := store.GetBookmark(r.Context(), bookmarksstore.GetBookmarkParams{ID: id, Owner: sess.Subject}); errors.Is(err, sql.ErrNoRows) {
		view.NotFound(ctx, w, r)
		return
	} else if err != nil {
		view.Fail(ctx, w, r, "bookmarks: loading bookmarks", err)
		return
	}
	if err := store.DeleteBookmark(r.Context(), bookmarksstore.DeleteBookmarkParams{ID: id, Owner: sess.Subject}); err != nil {
		view.Fail(ctx, w, r, "bookmarks: deleting bookmarks", err)
		return
	}
	http.Redirect(w, r, "/bookmarks", http.StatusSeeOther)
}
`

func TestEmitActionsScopedGoldenFiles(t *testing.T) {
	appRoot := newActionsAppRoot(t)
	genDir := t.TempDir()
	r := scopedFixtureResource()

	if _, _, err := EmitActions(appRoot, genDir, r); err != nil {
		t.Fatalf("EmitActions: %v", err)
	}

	cases := []struct{ path, want string }{
		{filepath.Join(genDir, "actions", "bookmarks", "index_get", "index.GET.go"), goldenScopedIndexGETGo},
		{filepath.Join(genDir, "actions", "bookmarks", "index_post", "index.POST.go"), goldenScopedIndexPOSTGo},
		{filepath.Join(genDir, "actions", "bookmarks", "id", "delete_post", "delete.POST.go"), goldenScopedDeletePOSTGo},
	}
	for _, c := range cases {
		got, err := os.ReadFile(c.path)
		if err != nil {
			t.Fatalf("read %s: %v", c.path, err)
		}
		if string(got) != c.want {
			t.Errorf("%s:\ngot:\n%s\nwant:\n%s", c.path, got, c.want)
		}
	}
}

// TestEmitActionsScopedOneBindCount pins the scoped one-bind corner
// (scopedPlainFixtureResource: no Search, no Filter, so the owner is
// Count's ONLY bind parameter, passed bare under sqlc's convention),
// and that new.GET — which touches no data — emits no session check
// at all (an unused sess would not even compile).
func TestEmitActionsScopedOneBindCount(t *testing.T) {
	appRoot := newActionsAppRoot(t)
	genDir := t.TempDir()

	if _, _, err := EmitActions(appRoot, genDir, scopedPlainFixtureResource()); err != nil {
		t.Fatalf("EmitActions: %v", err)
	}

	got, err := os.ReadFile(filepath.Join(genDir, "actions", "journals", "index_get", "index.GET.go"))
	if err != nil {
		t.Fatal(err)
	}
	if want := "store.CountJournals(r.Context(), sess.Subject)"; !strings.Contains(string(got), want) {
		t.Errorf("journals index.GET does not contain %q:\n%s", want, got)
	}

	newGET, err := os.ReadFile(filepath.Join(genDir, "actions", "journals", "new_get", "new.GET.go"))
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(newGET), "sessions.Current") {
		t.Errorf("new.GET should not resolve a session (it touches no data):\n%s", newGET)
	}
}

func TestEmitActionsGoldenFiles(t *testing.T) {
	appRoot := newActionsAppRoot(t)
	genDir := t.TempDir()
	r := fixtureResource()

	written, skipped, err := EmitActions(appRoot, genDir, r)
	if err != nil {
		t.Fatalf("EmitActions: %v", err)
	}
	if len(skipped) != 0 {
		t.Fatalf("skipped = %v, want none", skipped)
	}
	wantWritten := []string{
		filepath.Join(genDir, "actions", "admin", "notes", "index_get", "index.GET.go"),
		filepath.Join(genDir, "actions", "admin", "notes", "index_post", "index.POST.go"),
		filepath.Join(genDir, "actions", "admin", "notes", "new_get", "new.GET.go"),
		filepath.Join(genDir, "actions", "admin", "notes", "id", "index_get", "index.GET.go"),
		filepath.Join(genDir, "actions", "admin", "notes", "id", "edit_get", "edit.GET.go"),
		filepath.Join(genDir, "actions", "admin", "notes", "id", "edit_basics_post", "edit-basics.POST.go"),
		filepath.Join(genDir, "actions", "admin", "notes", "id", "delete_get", "delete.GET.go"),
		filepath.Join(genDir, "actions", "admin", "notes", "id", "delete_post", "delete.POST.go"),
		filepath.Join(genDir, "actions", "admin", "notes", "id", "edit_advanced_post", "edit-advanced.POST.go"),
	}
	if len(written) != len(wantWritten) {
		t.Fatalf("written = %v, want %v", written, wantWritten)
	}
	for i := range wantWritten {
		if written[i] != wantWritten[i] {
			t.Errorf("written[%d] = %q, want %q", i, written[i], wantWritten[i])
		}
	}

	cases := []struct{ path, want string }{
		{filepath.Join(genDir, "actions", "admin", "notes", "index_get", "index.GET.go"), goldenIndexGETGo},
		{filepath.Join(genDir, "actions", "admin", "notes", "id", "edit_basics_post", "edit-basics.POST.go"), goldenEditBasicsPOSTGo},
		{filepath.Join(genDir, "actions", "admin", "notes", "id", "edit_get", "edit.GET.go"), goldenEditGETGo},
		{filepath.Join(genDir, "actions", "admin", "notes", "id", "edit_advanced_post", "edit-advanced.POST.go"), goldenEditAdvancedPOSTGo},
	}
	for _, c := range cases {
		got, err := os.ReadFile(c.path)
		if err != nil {
			t.Fatalf("read %s: %v", c.path, err)
		}
		if string(got) != c.want {
			t.Errorf("%s:\ngot:\n%s\nwant:\n%s", c.path, got, c.want)
		}
	}
}

func TestEmitActionsIsIdempotent(t *testing.T) {
	appRoot := newActionsAppRoot(t)
	genDir := t.TempDir()
	r := fixtureResource()

	written, _, err := EmitActions(appRoot, genDir, r)
	if err != nil {
		t.Fatalf("EmitActions (1st): %v", err)
	}
	first := readAllFiles(t, written)

	if _, _, err := EmitActions(appRoot, genDir, r); err != nil {
		t.Fatalf("EmitActions (2nd): %v", err)
	}
	second := readAllFiles(t, written)

	for _, p := range written {
		if first[p] != second[p] {
			t.Errorf("%s changed between runs", p)
		}
	}
}

func TestEmitActionsSkipsHandWrittenFile(t *testing.T) {
	appRoot := newActionsAppRoot(t)
	genDir := t.TempDir()
	r := fixtureResource()

	handDir := filepath.Join(appRoot, "actions", "admin", "notes")
	if err := os.MkdirAll(handDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(handDir, "index.GET.go"), []byte("hand-written"), 0o644); err != nil {
		t.Fatal(err)
	}

	written, skipped, err := EmitActions(appRoot, genDir, r)
	if err != nil {
		t.Fatalf("EmitActions: %v", err)
	}

	wantSkipped := filepath.Join(genDir, "actions", "admin", "notes", "index_get", "index.GET.go")
	if len(skipped) != 1 || skipped[0] != wantSkipped {
		t.Fatalf("skipped = %v, want [%s]", skipped, wantSkipped)
	}
	if len(written) != 8 {
		t.Fatalf("written = %v, want 8 files (index.GET skipped)", written)
	}
	for _, w := range written {
		if w == wantSkipped {
			t.Errorf("skipped path %s also present in written", wantSkipped)
		}
	}
	if _, err := os.Stat(wantSkipped); !os.IsNotExist(err) {
		t.Errorf("skipped file %s was written to gen/ anyway", wantSkipped)
	}
}

// noAdvancedFixtureResource is fixtureResource with an empty
// Form.Advanced — exercises the path where edit-advanced.POST must not
// be emitted at all.
func noAdvancedFixtureResource() rastrillo.Resource {
	r := rastrillo.Resource{
		Name:  "widgets",
		Route: "/admin/widgets",
		Store: rastrillo.Exclusive,
		List: rastrillo.List{
			Columns: []rastrillo.Column{{Field: "Name"}},
		},
		Form: rastrillo.Form{
			Basics: []rastrillo.Field{{Name: "Name"}},
		},
	}
	if err := r.Validate(); err != nil {
		panic(err)
	}
	return r
}

// searchOnlyFixtureResource declares List.Search but no List.Filter —
// the exact shape of the blog's real "posts" manifest
// (examples/blog/manifest/posts.toml), whose committed
// gen/store/posts/queries.sql.go is what first exposed Critical 1:
// CountPosts(ctx, search interface{}) with NO CountPostsParams struct,
// because a query with exactly one bind parameter gets that parameter
// passed bare rather than wrapped in a struct sqlc doesn't generate.
// EmitActions used to emit a CountArticlesParams{Search: search} call
// for this shape (matching notes' two-bind case, wrongly), which fails
// to compile against real sqlc output — see actionIndexGET's countBinds
// switch and TestRunSqlcGeneratesCompilingStore's third fixture.
func searchOnlyFixtureResource() rastrillo.Resource {
	r := rastrillo.Resource{
		Name:  "articles",
		Route: "/admin/articles",
		Store: rastrillo.Exclusive,
		List: rastrillo.List{
			Columns: []rastrillo.Column{{Field: "Title"}},
			Search:  true,
		},
		Form: rastrillo.Form{
			Basics: []rastrillo.Field{{Name: "Title"}},
		},
	}
	if err := r.Validate(); err != nil {
		panic(err)
	}
	return r
}

// filterOnlyFixtureResource declares a single List.Filter entry but no
// List.Search — the mirror-image one-bind-parameter shape
// searchOnlyFixtureResource covers (Critical 1's fix note calls out
// both: "a search-only (or single-filter-only) resource"). Not
// exercised against real sqlc (searchOnlyFixtureResource already is,
// in sqlcrun_test.go), but TestActionIndexGETCountCallShape below pins
// its generated Count call's exact bare-argument shape all the same.
func filterOnlyFixtureResource() rastrillo.Resource {
	r := rastrillo.Resource{
		Name:  "tags",
		Route: "/admin/tags",
		Store: rastrillo.Exclusive,
		List: rastrillo.List{
			Columns: []rastrillo.Column{{Field: "Title"}},
			Filter:  []string{"Title"},
		},
		Form: rastrillo.Form{
			Basics: []rastrillo.Field{{Name: "Title"}},
		},
	}
	if err := r.Validate(); err != nil {
		panic(err)
	}
	return r
}

// TestActionIndexGETCountCallShape locks in actionIndexGET's countBinds
// switch across all four bind-count shapes sqlc's sqlite codegen
// distinguishes: zero (widgets — neither Search nor Filter), exactly
// one via Search alone (articles), exactly one via a single Filter
// alone (tags), and two or more (notes — both Search and a Filter).
// Only the middle two are new: the zero and two-or-more cases already
// worked before this fix (see the report for how the one-bind case was
// discovered, via the blog's real CountPosts).
func TestActionIndexGETCountCallShape(t *testing.T) {
	cases := []struct {
		name    string
		r       rastrillo.Resource
		want    string // substring the Count call must contain
		notWant string // substring that must NOT appear (the old, wrong shape)
	}{
		{"zero binds: neither Search nor Filter", noAdvancedFixtureResource(),
			"total, err := store.CountWidgets(r.Context())\n", "CountWidgetsParams"},
		{"one bind: Search alone", searchOnlyFixtureResource(),
			"total, err := store.CountArticles(r.Context(), search)\n", "CountArticlesParams"},
		{"one bind: a single Filter alone", filterOnlyFixtureResource(),
			"total, err := store.CountTags(r.Context(), filterTitle)\n", "CountTagsParams"},
		{"two binds: Search and a Filter", fixtureResource(),
			"total, err := store.CountNotes(r.Context(), notesstore.CountNotesParams{\n", ""},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := actionIndexGET(tc.r, "scratch")
			if !strings.Contains(got, tc.want) {
				t.Errorf("actionIndexGET(%s) missing %q\ngot:\n%s", tc.r.Name, tc.want, got)
			}
			if tc.notWant != "" && strings.Contains(got, tc.notWant) {
				t.Errorf("actionIndexGET(%s) unexpectedly contains %q (the pre-fix shape)", tc.r.Name, tc.notWant)
			}
		})
	}
}

func TestEmitActionsOmitsEditAdvancedWhenNoAdvancedFields(t *testing.T) {
	appRoot := newActionsAppRoot(t)
	genDir := t.TempDir()
	r := noAdvancedFixtureResource()

	written, skipped, err := EmitActions(appRoot, genDir, r)
	if err != nil {
		t.Fatalf("EmitActions: %v", err)
	}
	if len(skipped) != 0 {
		t.Fatalf("skipped = %v, want none", skipped)
	}
	if len(written) != 8 {
		t.Fatalf("written = %v, want exactly 8 files (no edit-advanced.POST)", written)
	}
	for _, w := range written {
		if strings.Contains(w, "edit_advanced") {
			t.Errorf("written contains an edit-advanced file for a resource with no Advanced fields: %s", w)
		}
	}
}

// ── Compile test ─────────────────────────────────────────────────────
//
// stubNotesStore mirrors the real sqlc output for the fixture resource
// exactly (verified by hand against a real `go tool sqlc generate` run
// during development — see the report): DBTX/New/Queries, the Note
// row struct, and every query method/Params struct EmitActions'
// generated Handle functions call. Using a hand-written stub rather
// than shelling out to sqlc keeps this test fast and network-free;
// TestRunSqlcGeneratesCompilingStore (sqlcrun_test.go) is what proves
// the real sqlc output matches this shape.
const stubNotesStore = `package notesstore

import "context"

type DBTX interface{}

func New(db DBTX) *Queries { return &Queries{db: db} }

type Queries struct{ db DBTX }

type Note struct {
	ID        int64
	Title     string
	Price     int64
	Body      string
	CreatedAt string
	UpdatedAt string
}

type ListNotesParams struct {
	Search      interface{}
	FilterTitle interface{}
	PageOffset  int64
	PageLimit   int64
}

func (q *Queries) ListNotes(ctx context.Context, arg ListNotesParams) ([]Note, error) {
	return nil, nil
}

type CountNotesParams struct {
	Search      interface{}
	FilterTitle interface{}
}

func (q *Queries) CountNotes(ctx context.Context, arg CountNotesParams) (int64, error) {
	return 0, nil
}

func (q *Queries) GetNote(ctx context.Context, id int64) (Note, error) {
	return Note{}, nil
}

func (q *Queries) DeleteNote(ctx context.Context, id int64) error {
	return nil
}

type CreateNoteParams struct {
	Title string
	Price int64
	Body  string
	Now   string
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (int64, error) {
	return 0, nil
}

type UpdateNoteBasicsParams struct {
	Title string
	Body  string
	Now   string
	ID    int64
}

func (q *Queries) UpdateNoteBasics(ctx context.Context, arg UpdateNoteBasicsParams) error {
	return nil
}

type UpdateNoteAdvancedParams struct {
	Price int64
	Now   string
	ID    int64
}

func (q *Queries) UpdateNoteAdvanced(ctx context.Context, arg UpdateNoteAdvancedParams) error {
	return nil
}
`

// stubWidgetsStore is the second resource's stub: List.Search false,
// no Filter — the opposite corner of the generation-time gates from
// notes (which has both), so the two fixtures together exercise every
// Search/Filter/Advanced combination this task's gates branch on.
const stubWidgetsStore = `package widgetsstore

import "context"

type DBTX interface{}

func New(db DBTX) *Queries { return &Queries{db: db} }

type Queries struct{ db DBTX }

type Widget struct {
	ID        int64
	Name      string
	CreatedAt string
	UpdatedAt string
}

type ListWidgetsParams struct {
	PageOffset int64
	PageLimit  int64
}

func (q *Queries) ListWidgets(ctx context.Context, arg ListWidgetsParams) ([]Widget, error) {
	return nil, nil
}

// CountWidgets takes no Params struct at all — verified against a
// real sqlc generate run: a query with zero bind parameters (widgets
// has neither Search nor a declared Filter) drops the arg entirely
// rather than generating an empty struct type.
func (q *Queries) CountWidgets(ctx context.Context) (int64, error) {
	return 0, nil
}

func (q *Queries) GetWidget(ctx context.Context, id int64) (Widget, error) {
	return Widget{}, nil
}

func (q *Queries) DeleteWidget(ctx context.Context, id int64) error {
	return nil
}

type CreateWidgetParams struct {
	Name string
	Now  string
}

func (q *Queries) CreateWidget(ctx context.Context, arg CreateWidgetParams) (int64, error) {
	return 0, nil
}

type UpdateWidgetBasicsParams struct {
	Name string
	Now  string
	ID   int64
}

func (q *Queries) UpdateWidgetBasics(ctx context.Context, arg UpdateWidgetBasicsParams) error {
	return nil
}
`

// stubArticlesStore is the third resource's stub: List.Search true,
// no Filter — the one-bind-parameter corner Critical 1's fix note
// covers (notes has two binds, widgets has zero; neither exercises the
// bare-argument case at all). CountArticles takes a bare `search
// interface{}`, no CountArticlesParams — exactly the shape the blog's
// real gen/store/posts/queries.sql.go has, which is what first exposed
// this bug (see the report).
const stubArticlesStore = `package articlesstore

import "context"

type DBTX interface{}

func New(db DBTX) *Queries { return &Queries{db: db} }

type Queries struct{ db DBTX }

type Article struct {
	ID        int64
	Title     string
	CreatedAt string
	UpdatedAt string
}

type ListArticlesParams struct {
	Search     interface{}
	PageOffset int64
	PageLimit  int64
}

func (q *Queries) ListArticles(ctx context.Context, arg ListArticlesParams) ([]Article, error) {
	return nil, nil
}

// CountArticles takes search bare, not wrapped in a Params struct —
// the one-bind-parameter case: a query with exactly one sqlc.arg gets
// that argument passed directly, matching neither notes' Params-struct
// case (two-plus binds) nor widgets' no-argument case (zero binds).
func (q *Queries) CountArticles(ctx context.Context, search interface{}) (int64, error) {
	return 0, nil
}

func (q *Queries) GetArticle(ctx context.Context, id int64) (Article, error) {
	return Article{}, nil
}

func (q *Queries) DeleteArticle(ctx context.Context, id int64) error {
	return nil
}

type CreateArticleParams struct {
	Title string
	Now   string
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (int64, error) {
	return 0, nil
}

type UpdateArticleBasicsParams struct {
	Title string
	Now   string
	ID    int64
}

func (q *Queries) UpdateArticleBasics(ctx context.Context, arg UpdateArticleBasicsParams) error {
	return nil
}
`

// stubTagsStore is the fourth resource's stub: a single List.Filter
// (Title), no Search — the mirror-image one-bind-parameter shape
// (filterOnlyFixtureResource's doc explains why this corner matters
// too, alongside articles' Search-alone corner).
const stubTagsStore = `package tagsstore

import "context"

type DBTX interface{}

func New(db DBTX) *Queries { return &Queries{db: db} }

type Queries struct{ db DBTX }

type Tag struct {
	ID        int64
	Title     string
	CreatedAt string
	UpdatedAt string
}

type ListTagsParams struct {
	FilterTitle interface{}
	PageOffset  int64
	PageLimit   int64
}

func (q *Queries) ListTags(ctx context.Context, arg ListTagsParams) ([]Tag, error) {
	return nil, nil
}

// CountTags takes its one Filter bind bare — same one-bind-parameter
// convention as stubArticlesStore's CountArticles, just reached via a
// Filter instead of Search.
func (q *Queries) CountTags(ctx context.Context, filterTitle interface{}) (int64, error) {
	return 0, nil
}

func (q *Queries) GetTag(ctx context.Context, id int64) (Tag, error) {
	return Tag{}, nil
}

func (q *Queries) DeleteTag(ctx context.Context, id int64) error {
	return nil
}

type CreateTagParams struct {
	Title string
	Now   string
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (int64, error) {
	return 0, nil
}

type UpdateTagBasicsParams struct {
	Title string
	Now   string
	ID    int64
}

func (q *Queries) UpdateTagBasics(ctx context.Context, arg UpdateTagBasicsParams) error {
	return nil
}
`

// TestEmitActionsCompile builds a standalone module (replacing this
// repo, same pattern as sqlcrun_test.go's newScratchModule) containing
// EmitActions' output for the fixture plus the hand-written store stub
// above, and runs go build ./... in it — the brief's "emitted actions
// + a stub store package compile" requirement. No network: this is
// what makes it safe to run on every go test ./..., unlike
// TestRunSqlcGeneratesCompilingStore's real sqlc fetch. Four resources,
// not two: notes (two Count binds) and widgets (zero) were the
// original two corners; articles (one bind via Search alone) and tags
// (one bind via a single Filter alone) are Critical 1's fix — without
// them this test could not have caught the one-bind Params-struct bug
// TestRunSqlcGeneratesCompilingStore's real sqlc fetch found.

// stubBookmarksStore is the scoped (scope = "user") stub: every
// Params struct carries Owner, and Get/Delete take a two-field Params
// struct instead of a bare id — the shapes
// TestRunSqlcGeneratesCompilingStore verifies against real sqlc.
const stubBookmarksStore = `package bookmarksstore

import "context"

type DBTX interface{}

func New(db DBTX) *Queries { return &Queries{db: db} }

type Queries struct{ db DBTX }

type Bookmark struct {
	ID        int64
	Owner     string
	Title     string
	Link      string
	Notes     string
	CreatedAt string
	UpdatedAt string
}

type ListBookmarksParams struct {
	Owner      string
	Search     interface{}
	PageOffset int64
	PageLimit  int64
}

func (q *Queries) ListBookmarks(ctx context.Context, arg ListBookmarksParams) ([]Bookmark, error) {
	return nil, nil
}

type CountBookmarksParams struct {
	Owner  string
	Search interface{}
}

func (q *Queries) CountBookmarks(ctx context.Context, arg CountBookmarksParams) (int64, error) {
	return 0, nil
}

type GetBookmarkParams struct {
	ID    int64
	Owner string
}

func (q *Queries) GetBookmark(ctx context.Context, arg GetBookmarkParams) (Bookmark, error) {
	return Bookmark{}, nil
}

type DeleteBookmarkParams struct {
	ID    int64
	Owner string
}

func (q *Queries) DeleteBookmark(ctx context.Context, arg DeleteBookmarkParams) error {
	return nil
}

type CreateBookmarkParams struct {
	Owner string
	Title string
	Link  string
	Notes string
	Now   string
}

func (q *Queries) CreateBookmark(ctx context.Context, arg CreateBookmarkParams) (int64, error) {
	return 0, nil
}

type UpdateBookmarkBasicsParams struct {
	Title string
	Link  string
	Owner string
	Now   string
	ID    int64
}

func (q *Queries) UpdateBookmarkBasics(ctx context.Context, arg UpdateBookmarkBasicsParams) error {
	return nil
}

type UpdateBookmarkAdvancedParams struct {
	Notes string
	Owner string
	Now   string
	ID    int64
}

func (q *Queries) UpdateBookmarkAdvanced(ctx context.Context, arg UpdateBookmarkAdvancedParams) error {
	return nil
}
`

// stubJournalsStore is the scoped one-bind stub: no Search and no
// Filter, so CountJournals' only bind parameter is the owner, passed
// bare — the scoped twin of stubArticlesStore's convention corner.
const stubJournalsStore = `package journalsstore

import "context"

type DBTX interface{}

func New(db DBTX) *Queries { return &Queries{db: db} }

type Queries struct{ db DBTX }

type Journal struct {
	ID        int64
	Owner     string
	Name      string
	CreatedAt string
	UpdatedAt string
}

type ListJournalsParams struct {
	Owner      string
	PageOffset int64
	PageLimit  int64
}

func (q *Queries) ListJournals(ctx context.Context, arg ListJournalsParams) ([]Journal, error) {
	return nil, nil
}

func (q *Queries) CountJournals(ctx context.Context, owner string) (int64, error) {
	return 0, nil
}

type GetJournalParams struct {
	ID    int64
	Owner string
}

func (q *Queries) GetJournal(ctx context.Context, arg GetJournalParams) (Journal, error) {
	return Journal{}, nil
}

type DeleteJournalParams struct {
	ID    int64
	Owner string
}

func (q *Queries) DeleteJournal(ctx context.Context, arg DeleteJournalParams) error {
	return nil
}

type CreateJournalParams struct {
	Owner string
	Name  string
	Now   string
}

func (q *Queries) CreateJournal(ctx context.Context, arg CreateJournalParams) (int64, error) {
	return 0, nil
}

type UpdateJournalBasicsParams struct {
	Name  string
	Owner string
	Now   string
	ID    int64
}

func (q *Queries) UpdateJournalBasics(ctx context.Context, arg UpdateJournalBasicsParams) error {
	return nil
}
`

func TestEmitActionsCompile(t *testing.T) {
	root := newScratchModule(t, false)
	genDir := filepath.Join(root, "gen")

	if _, _, err := EmitActions(root, genDir, fixtureResource()); err != nil {
		t.Fatalf("EmitActions(notes): %v", err)
	}
	if _, _, err := EmitActions(root, genDir, noAdvancedFixtureResource()); err != nil {
		t.Fatalf("EmitActions(widgets): %v", err)
	}
	if _, _, err := EmitActions(root, genDir, searchOnlyFixtureResource()); err != nil {
		t.Fatalf("EmitActions(articles): %v", err)
	}
	if _, _, err := EmitActions(root, genDir, filterOnlyFixtureResource()); err != nil {
		t.Fatalf("EmitActions(tags): %v", err)
	}
	if _, _, err := EmitActions(root, genDir, scopedFixtureResource()); err != nil {
		t.Fatalf("EmitActions(bookmarks): %v", err)
	}
	if _, _, err := EmitActions(root, genDir, scopedPlainFixtureResource()); err != nil {
		t.Fatalf("EmitActions(journals): %v", err)
	}

	writeStub := func(resource, content string) {
		t.Helper()
		dir := filepath.Join(genDir, "store", resource)
		if err := os.MkdirAll(dir, 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(dir, "store.go"), []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	writeStub("notes", stubNotesStore)
	writeStub("widgets", stubWidgetsStore)
	writeStub("articles", stubArticlesStore)
	writeStub("tags", stubTagsStore)
	writeStub("bookmarks", stubBookmarksStore)
	writeStub("journals", stubJournalsStore)

	cmd := exec.Command("go", "build", "./...")
	cmd.Dir = root
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("go build ./... in scratch module: %v\n%s", err, out)
	}
}

// TestMoneyHelpersRoundTrip drops a small real _test.go into one of
// EmitActions' generated packages and runs `go test` against it, so
// the assertions below exercise the REAL form.FormatCents/
// FormatCentsPlain/ParseCents the generated package imports (Task 6's
// shared form package — see actions.go's actionImportLines), not a
// hand-copied stand-in in this test file that could quietly drift from
// what's really emitted. This is the money patch's regression net: the
// edit-seed round trip ("1.00" out of FormatCentsPlain, "1.00" — not
// "$1.00" — back in through ParseCents without error) is exactly the
// bug an unchanged edit-form resubmission used to hit as a 400.
func TestMoneyHelpersRoundTrip(t *testing.T) {
	// newScratchModule (not newActionsAppRoot): this test actually
	// invokes `go test` against the generated package, which needs
	// amadan.net/rastrillo/rastrillo (for rastrillo.Ctx et al.)
	// to resolve to THIS working tree via a replace directive — plain
	// newActionsAppRoot's go.mod has no such directive, so `go test`
	// would instead fetch whatever version is published, which may not
	// even have the fields this branch's generated code references.
	appRoot := newScratchModule(t, false)
	genDir := filepath.Join(appRoot, "gen")
	r := fixtureResource()

	written, _, err := EmitActions(appRoot, genDir, r)
	if err != nil {
		t.Fatalf("EmitActions: %v", err)
	}

	var dir string
	for _, w := range written {
		if strings.Contains(w, "new_get") {
			dir = filepath.Dir(w)
		}
	}
	if dir == "" {
		t.Fatalf("no new_get file among written: %v", written)
	}
	genPath := filepath.Join(dir, "new.GET.go")
	src, err := os.ReadFile(genPath)
	if err != nil {
		t.Fatalf("read %s: %v", genPath, err)
	}
	m := regexp.MustCompile(`(?m)^package (\S+)`).FindSubmatch(src)
	if m == nil {
		t.Fatalf("no package clause found in %s", genPath)
	}
	pkg := string(m[1])

	testSrc := `package ` + pkg + `

import (
	"testing"

	"amadan.net/rastrillo/rastrillo/form"
)

// TestParseCentsAndFormatCentsPlainRoundTrip pins the money patch: an
// edit form seeded via form.FormatCentsPlain must parse back through
// form.ParseCents to the exact same cents value (the "unchanged
// resubmission" case), form.FormatCents/FormatCentsPlain must produce
// the plain decimal shapes an edit seed round-trips through, and
// form.ParseCents must reject "$1.00" (the pre-fix seed shape),
// "12.-5" and "12.+5" (a sign smuggled into either half via
// strconv.ParseInt's own leniency), and any negative amount outright
// (v1 has no use for negative prices).
func TestParseCentsAndFormatCentsPlainRoundTrip(t *testing.T) {
	for _, cents := range []int64{0, 1, 100, 150, 12345} {
		seed := form.FormatCentsPlain(cents)
		got, err := form.ParseCents(seed)
		if err != nil {
			t.Errorf("form.ParseCents(form.FormatCentsPlain(%d)) = %q: unexpected error %v", cents, seed, err)
			continue
		}
		if got != cents {
			t.Errorf("form.ParseCents(form.FormatCentsPlain(%d)) = %d, want %d (seed was %q)", cents, got, cents, seed)
		}
	}

	if got := form.FormatCentsPlain(100); got != "1.00" {
		t.Errorf(` + "`form.FormatCentsPlain(100) = %q, want \"1.00\"`" + `, got)
	}
	if got := form.FormatCents(100); got != "$1.00" {
		t.Errorf(` + "`form.FormatCents(100) = %q, want \"$1.00\"`" + `, got)
	}

	for _, in := range []string{"1", "1.5", "1.50", "1.00"} {
		if _, err := form.ParseCents(in); err != nil {
			t.Errorf("form.ParseCents(%q): unexpected error %v", in, err)
		}
	}

	for _, in := range []string{"$1.00", "12.-5", "12.+5", "-5.00", "-5"} {
		if _, err := form.ParseCents(in); err == nil {
			t.Errorf("form.ParseCents(%q): accepted, want a field error", in)
		}
	}
}
`
	testPath := filepath.Join(dir, "money_roundtrip_test.go")
	if err := os.WriteFile(testPath, []byte(testSrc), 0o644); err != nil {
		t.Fatalf("write %s: %v", testPath, err)
	}

	relPkgDir, err := filepath.Rel(appRoot, dir)
	if err != nil {
		t.Fatalf("filepath.Rel: %v", err)
	}
	cmd := exec.Command("go", "test", "./"+filepath.ToSlash(relPkgDir)+"/...")
	cmd.Dir = appRoot
	out, err := cmd.CombinedOutput()
	t.Logf("go test %s output:\n%s", relPkgDir, out)
	if err != nil {
		t.Fatalf("go test in generated package failed: %v\n%s", err, out)
	}
}

// ── Required: real-execution coverage ───────────────────────────────

// requiredFixtureResource is a real-execution-only fixture (not used
// for golden-pinning — filteredFixtureResource's Title:Required already
// pins the shape of the emitted check block, see
// goldenFilteredIndexPOSTGo/goldenFilteredEditBasicsPOSTGo above): Title
// (Text, Required) AND Price (Money, Required) together, in one
// resource, so TestRequiredValidation can exercise every case the brief
// calls out — blank Text, blank Money, "0" Money (accepted), a
// present-but-invalid Money value (the parse error, never the required
// one) — against REAL generated code over real HTTP requests, without
// perturbing filteredFixtureResource() itself (Task 3's fixture, shared
// across tasks and pinned by its own goldens).
func requiredFixtureResource() rastrillo.Resource {
	r := rastrillo.Resource{
		Name:  "invoices",
		Route: "/admin/invoices",
		Store: rastrillo.Exclusive,
		List: rastrillo.List{
			Columns: []rastrillo.Column{{Field: "Title"}, {Field: "Price", Kind: rastrillo.Money}},
		},
		Form: rastrillo.Form{
			Basics: []rastrillo.Field{
				{Name: "Title", Required: true},
				{Name: "Price", Kind: rastrillo.Money, Required: true},
			},
		},
	}
	if err := r.Validate(); err != nil {
		panic(err)
	}
	return r
}

// stubInvoicesStore is the minimal store TestRequiredValidation's real
// HTTP requests need: CreateInvoice (index.POST's happy path),
// GetInvoice (edit-basics.POST's Get-or-404), UpdateInvoiceBasics
// (edit-basics.POST's happy path) — the only three store calls either
// Handle makes; this test never exercises index.GET, so no List/Count
// method is needed.
const stubInvoicesStore = `package invoicesstore

import "context"

type DBTX interface{}

func New(db DBTX) *Queries { return &Queries{db: db} }

type Queries struct{ db DBTX }

type Invoice struct {
	ID        int64
	Title     string
	Price     int64
	CreatedAt string
	UpdatedAt string
}

type CreateInvoiceParams struct {
	Title string
	Price int64
	Now   string
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (int64, error) {
	return 1, nil
}

func (q *Queries) GetInvoice(ctx context.Context, id int64) (Invoice, error) {
	return Invoice{ID: id, Title: "Existing Invoice", Price: 500}, nil
}

func (q *Queries) DeleteInvoice(ctx context.Context, id int64) error {
	return nil
}

type UpdateInvoiceBasicsParams struct {
	Title string
	Price int64
	Now   string
	ID    int64
}

func (q *Queries) UpdateInvoiceBasics(ctx context.Context, arg UpdateInvoiceBasicsParams) error {
	return nil
}
`

// TestRequiredValidation drops httptest-driven _test.go files into
// EmitActions' REAL generated index.POST and edit-basics.POST packages
// for requiredFixtureResource() and runs them with `go test`
// (TestMoneyHelpersRoundTrip's pattern above: a real generated package,
// not a hand-copied stand-in that could drift). It covers every case
// the brief calls out: blank Title -> 400 containing "required"; blank
// Price (raw "") -> 400 containing "required"; "0" Price -> accepted
// (the real store call happens, the stub returns success); a
// present-but-invalid Price -> the parse error, never the required one.
// The emitted check block's exact SHAPE is separately golden-pinned
// (goldenFilteredIndexPOSTGo/goldenFilteredEditBasicsPOSTGo, above,
// against filteredFixtureResource()'s Title-only/Text-only case) — this
// test is the real-execution half the brief asks for alongside that
// pin, run at the action level rather than a full HTTP-server/DB round
// trip (Task 6's tickets suite is where that fuller level lives).
func TestRequiredValidation(t *testing.T) {
	appRoot := newScratchModule(t, false)
	genDir := filepath.Join(appRoot, "gen")
	r := requiredFixtureResource()

	written, _, err := EmitActions(appRoot, genDir, r)
	if err != nil {
		t.Fatalf("EmitActions: %v", err)
	}

	dirFor := func(marker string) string {
		for _, w := range written {
			if strings.Contains(w, marker) {
				return filepath.Dir(w)
			}
		}
		t.Fatalf("no %s file among written: %v", marker, written)
		return ""
	}
	createDir := dirFor("index_post")
	editBasicsDir := dirFor("edit_basics_post")

	pkgOf := func(dir, base string) string {
		src, err := os.ReadFile(filepath.Join(dir, base))
		if err != nil {
			t.Fatalf("read %s: %v", base, err)
		}
		m := regexp.MustCompile(`(?m)^package (\S+)`).FindSubmatch(src)
		if m == nil {
			t.Fatalf("no package clause found in %s", base)
		}
		return string(m[1])
	}
	createPkg := pkgOf(createDir, "index.POST.go")
	editPkg := pkgOf(editBasicsDir, "edit-basics.POST.go")

	storeDir := filepath.Join(genDir, "store", "invoices")
	if err := os.MkdirAll(storeDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(storeDir, "store.go"), []byte(stubInvoicesStore), 0o644); err != nil {
		t.Fatal(err)
	}

	createTestSrc := `package ` + createPkg + `

import (
	"net/http"
	"net/http/httptest"
	"net/url"
	"strings"
	"testing"

	"amadan.net/rastrillo/rastrillo"
)

func doCreate(t *testing.T, form url.Values) (*httptest.ResponseRecorder, formView) {
	t.Helper()
	var captured formView
	ctx := &rastrillo.Ctx{
		Render: func(ctx *rastrillo.Ctx, w http.ResponseWriter, page string, status int, data any) {
			captured, _ = data.(formView)
			w.WriteHeader(status)
		},
	}
	req := httptest.NewRequest(http.MethodPost, "/admin/invoices", strings.NewReader(form.Encode()))
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	w := httptest.NewRecorder()
	Handle(ctx, w, req)
	return w, captured
}

func TestCreateBlankTitleIs400Required(t *testing.T) {
	w, fv := doCreate(t, url.Values{"Title": {""}, "Price": {"5.00"}})
	if w.Code != http.StatusBadRequest {
		t.Fatalf("status = %d, want 400", w.Code)
	}
	if !strings.Contains(fv.Errors["Title"], "required") {
		t.Errorf("Errors[Title] = %q, want it to contain \"required\"", fv.Errors["Title"])
	}
}

func TestCreateBlankPriceIs400Required(t *testing.T) {
	w, fv := doCreate(t, url.Values{"Title": {"A title"}, "Price": {""}})
	if w.Code != http.StatusBadRequest {
		t.Fatalf("status = %d, want 400", w.Code)
	}
	if !strings.Contains(fv.Errors["Price"], "required") {
		t.Errorf("Errors[Price] = %q, want it to contain \"required\"", fv.Errors["Price"])
	}
}

func TestCreateZeroPriceIsAccepted(t *testing.T) {
	w, _ := doCreate(t, url.Values{"Title": {"A title"}, "Price": {"0"}})
	if w.Code != http.StatusSeeOther {
		t.Fatalf("status = %d, want 303 (\"0\" is a valid required Money value)", w.Code)
	}
}

func TestCreateInvalidPriceIsParseErrorNotRequired(t *testing.T) {
	w, fv := doCreate(t, url.Values{"Title": {"A title"}, "Price": {"not-a-number"}})
	if w.Code != http.StatusBadRequest {
		t.Fatalf("status = %d, want 400", w.Code)
	}
	if strings.Contains(fv.Errors["Price"], "required") {
		t.Errorf("Errors[Price] = %q, want the parse error, not the required one", fv.Errors["Price"])
	}
	if fv.Errors["Price"] == "" {
		t.Errorf("Errors[Price] is empty, want a parse-error message")
	}
}
`
	if err := os.WriteFile(filepath.Join(createDir, "required_test.go"), []byte(createTestSrc), 0o644); err != nil {
		t.Fatal(err)
	}

	editTestSrc := `package ` + editPkg + `

import (
	"net/http"
	"net/http/httptest"
	"net/url"
	"strings"
	"testing"

	"amadan.net/rastrillo/rastrillo"
)

func doEditBasics(t *testing.T, form url.Values) (*httptest.ResponseRecorder, formView) {
	t.Helper()
	var captured formView
	ctx := &rastrillo.Ctx{
		Render: func(ctx *rastrillo.Ctx, w http.ResponseWriter, page string, status int, data any) {
			captured, _ = data.(formView)
			w.WriteHeader(status)
		},
	}
	req := httptest.NewRequest(http.MethodPost, "/admin/invoices/1/edit-basics", strings.NewReader(form.Encode()))
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	req.SetPathValue("id", "1")
	w := httptest.NewRecorder()
	Handle(ctx, w, req)
	return w, captured
}

func TestEditBasicsBlankTitleIs400Required(t *testing.T) {
	w, fv := doEditBasics(t, url.Values{"Title": {"   "}, "Price": {"5.00"}})
	if w.Code != http.StatusBadRequest {
		t.Fatalf("status = %d, want 400", w.Code)
	}
	if !strings.Contains(fv.Errors["Title"], "required") {
		t.Errorf("Errors[Title] = %q, want it to contain \"required\"", fv.Errors["Title"])
	}
}

func TestEditBasicsBlankPriceIs400Required(t *testing.T) {
	w, fv := doEditBasics(t, url.Values{"Title": {"A title"}, "Price": {""}})
	if w.Code != http.StatusBadRequest {
		t.Fatalf("status = %d, want 400", w.Code)
	}
	if !strings.Contains(fv.Errors["Price"], "required") {
		t.Errorf("Errors[Price] = %q, want it to contain \"required\"", fv.Errors["Price"])
	}
}

func TestEditBasicsZeroPriceIsAccepted(t *testing.T) {
	w, _ := doEditBasics(t, url.Values{"Title": {"A title"}, "Price": {"0"}})
	if w.Code != http.StatusSeeOther {
		t.Fatalf("status = %d, want 303 (\"0\" is a valid required Money value)", w.Code)
	}
}

func TestEditBasicsInvalidPriceIsParseErrorNotRequired(t *testing.T) {
	w, fv := doEditBasics(t, url.Values{"Title": {"A title"}, "Price": {"12.345"}})
	if w.Code != http.StatusBadRequest {
		t.Fatalf("status = %d, want 400", w.Code)
	}
	if strings.Contains(fv.Errors["Price"], "required") {
		t.Errorf("Errors[Price] = %q, want the parse error, not the required one", fv.Errors["Price"])
	}
	if fv.Errors["Price"] == "" {
		t.Errorf("Errors[Price] is empty, want a parse-error message")
	}
}
`
	if err := os.WriteFile(filepath.Join(editBasicsDir, "required_test.go"), []byte(editTestSrc), 0o644); err != nil {
		t.Fatal(err)
	}

	relCreate, err := filepath.Rel(appRoot, createDir)
	if err != nil {
		t.Fatal(err)
	}
	relEdit, err := filepath.Rel(appRoot, editBasicsDir)
	if err != nil {
		t.Fatal(err)
	}
	cmd := exec.Command("go", "test",
		"./"+filepath.ToSlash(relCreate)+"/...",
		"./"+filepath.ToSlash(relEdit)+"/...",
	)
	cmd.Dir = appRoot
	out, err := cmd.CombinedOutput()
	t.Logf("go test output:\n%s", out)
	if err != nil {
		t.Fatalf("go test in generated packages failed: %v\n%s", err, out)
	}
}
