package generate

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/carlosframework/rastrillo"
)

// fixtureResource is the plan's running example (also validResource in the
// root package's manifest_test.go): a "notes" resource with a Title/Price
// list, Search on, a Title filter, and Title/Body basics plus a Price
// advanced field. EmitStore documents its input as validated with kinds
// already normalized, so this fixture runs through Validate — exactly
// what a real caller (the manifest loader) would hand it.
func fixtureResource() rastrillo.Resource {
	r := rastrillo.Resource{
		Name:  "notes",
		Route: "/admin/notes",
		Store: rastrillo.Exclusive,
		List: rastrillo.List{
			Columns: []rastrillo.Column{{Field: "Title"}, {Field: "Price", Kind: rastrillo.Money}},
			Search:  true,
			Filter:  []string{"Title"},
		},
		Form: rastrillo.Form{
			Basics:   []rastrillo.Field{{Name: "Title"}, {Name: "Body", Kind: rastrillo.Textarea}},
			Advanced: []rastrillo.Field{{Name: "Price", Kind: rastrillo.Money}},
		},
	}
	if err := r.Validate(); err != nil {
		panic(err) // fixture must stay valid; a break here is a test bug
	}
	return r
}

// filteredFixtureResource is the fixture from the plan's Fixture evolution
// section: an "events" resource with Status in both Filter and Filters,
// testing the deduping of filterFields. EmitStore requires Validate, so this
// fixture runs through it — exactly what a real caller (the manifest loader)
// would hand it.
func filteredFixtureResource() rastrillo.Resource {
	r := rastrillo.Resource{
		Name:  "events",
		Route: "/admin/events",
		Store: rastrillo.Exclusive,
		List: rastrillo.List{
			Columns: []rastrillo.Column{{Field: "Title"}, {Field: "Status"}},
			Search:  true,
			Filter:  []string{"Status"},
			Filters: []rastrillo.Filter{{Field: "Status", Values: []string{"draft", "live"}}},
		},
		Form: rastrillo.Form{
			Basics: []rastrillo.Field{
				{Name: "Title", Required: true},
				{Name: "Status"},
			},
		},
	}
	if err := r.Validate(); err != nil {
		panic(err) // fixture must stay valid; a break here is a test bug
	}
	return r
}

// scopedFixtureResource is the scope = "user" running example (the
// same shape examples/notes declares as manifest/bookmarks.toml): a
// user-scoped "bookmarks" resource with search, a Required basic, and
// an Advanced textarea, so the scoped goldens cover the always-on
// owner WHERE clause alongside search, both Update groups, and the
// validation re-render path.
func scopedFixtureResource() rastrillo.Resource {
	r := rastrillo.Resource{
		Name:  "bookmarks",
		Route: "/bookmarks",
		Store: rastrillo.Exclusive,
		Scope: rastrillo.UserScoped,
		List: rastrillo.List{
			Columns: []rastrillo.Column{{Field: "Title"}, {Field: "Link"}},
			Search:  true,
		},
		Form: rastrillo.Form{
			Basics:   []rastrillo.Field{{Name: "Title", Required: true}, {Name: "Link"}},
			Advanced: []rastrillo.Field{{Name: "Notes", Kind: rastrillo.Textarea}},
		},
	}
	if err := r.Validate(); err != nil {
		panic(err) // fixture must stay valid; a break here is a test bug
	}
	return r
}

// scopedPlainFixtureResource is the scoped counterpart of the
// one-bind corner: scope = "user" with no Search and no Filter, so
// Count's ONLY bind parameter is the owner — which sqlc passes bare,
// not wrapped in a Params struct (see actionIndexGET's countBinds
// switch and TestRunSqlcGeneratesCompilingStore).
func scopedPlainFixtureResource() rastrillo.Resource {
	r := rastrillo.Resource{
		Name:  "journals",
		Route: "/journals",
		Store: rastrillo.Exclusive,
		Scope: rastrillo.UserScoped,
		List: rastrillo.List{
			Columns: []rastrillo.Column{{Field: "Name"}},
		},
		Form: rastrillo.Form{
			Basics: []rastrillo.Field{{Name: "Name"}},
		},
	}
	if err := r.Validate(); err != nil {
		panic(err) // fixture must stay valid; a break here is a test bug
	}
	return r
}

const goldenSchemaSQL = `-- Code generated by rastrillo generate; DO NOT EDIT.
CREATE TABLE notes (
  id INTEGER PRIMARY KEY,
  title TEXT NOT NULL DEFAULT '',
  price INTEGER NOT NULL DEFAULT 0,
  body TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
`

const goldenQueriesSQL = `-- Code generated by rastrillo generate; DO NOT EDIT.

-- name: ListNotes :many
SELECT * FROM notes
WHERE (sqlc.arg(search) = '' OR title LIKE '%' || sqlc.arg(search) || '%')
  AND (sqlc.arg(filter_title) = '' OR title = sqlc.arg(filter_title))
ORDER BY created_at DESC, id DESC
LIMIT sqlc.arg(page_limit) OFFSET sqlc.arg(page_offset);

-- name: CountNotes :one
SELECT COUNT(*) FROM notes
WHERE (sqlc.arg(search) = '' OR title LIKE '%' || sqlc.arg(search) || '%')
  AND (sqlc.arg(filter_title) = '' OR title = sqlc.arg(filter_title));

-- name: GetNote :one
SELECT * FROM notes WHERE id = sqlc.arg(id);

-- name: CreateNote :one
INSERT INTO notes (title, price, body, created_at, updated_at)
VALUES (sqlc.arg(title), sqlc.arg(price), sqlc.arg(body), sqlc.arg(now), sqlc.arg(now))
RETURNING id;

-- name: UpdateNoteBasics :exec
UPDATE notes SET title = sqlc.arg(title), body = sqlc.arg(body), updated_at = sqlc.arg(now) WHERE id = sqlc.arg(id);

-- name: UpdateNoteAdvanced :exec
UPDATE notes SET price = sqlc.arg(price), updated_at = sqlc.arg(now) WHERE id = sqlc.arg(id);

-- name: DeleteNote :exec
DELETE FROM notes WHERE id = sqlc.arg(id);
`

const goldenSqlcYAML = `# Code generated by rastrillo generate; DO NOT EDIT.
version: "2"
sql:
  - engine: "sqlite"
    schema: "notes/schema.sql"
    queries: "notes/queries.sql"
    gen:
      go:
        package: "notesstore"
        out: "notes"
`

// bq holds a lone backtick so goldenMigrationsGo (whose content itself
// contains backticks) can be assembled without nesting raw string
// literals inside one another.
const bq = "`"

var goldenMigrationsGo = "// Code generated by rastrillo generate; DO NOT EDIT.\n" +
	"package notesstore\n\n" +
	"// Migrations is the schema for Options.Migrations. Additive changes\n" +
	"// beyond this initial CREATE are the app's own migrations.\n" +
	"var Migrations = []string{" + bq + `CREATE TABLE IF NOT EXISTS notes (
  id INTEGER PRIMARY KEY,
  title TEXT NOT NULL DEFAULT '',
  price INTEGER NOT NULL DEFAULT 0,
  body TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);` + bq + "}\n"

// goldenScopedSchemaSQL / goldenScopedQueriesSQL /
// goldenScopedMigrationsGo pin the whole scoped-store contract in one
// place: the owner column and its index; the always-on leading owner
// clause on List/Count (no empty-disables-it escape — see
// whereClauses); Create stamping the owner; and every per-record query
// (Get, both Updates, Delete) keyed on id AND owner (recordKey), which
// is what makes someone else's row sql.ErrNoRows.
const goldenScopedSchemaSQL = `-- Code generated by rastrillo generate; DO NOT EDIT.
CREATE TABLE bookmarks (
  id INTEGER PRIMARY KEY,
  owner TEXT NOT NULL,
  title TEXT NOT NULL DEFAULT '',
  link TEXT NOT NULL DEFAULT '',
  notes TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE INDEX bookmarks_owner ON bookmarks (owner);
`

const goldenScopedQueriesSQL = `-- Code generated by rastrillo generate; DO NOT EDIT.

-- name: ListBookmarks :many
SELECT * FROM bookmarks
WHERE owner = sqlc.arg(owner)
  AND (sqlc.arg(search) = '' OR (title LIKE '%' || sqlc.arg(search) || '%' OR link LIKE '%' || sqlc.arg(search) || '%'))
ORDER BY created_at DESC, id DESC
LIMIT sqlc.arg(page_limit) OFFSET sqlc.arg(page_offset);

-- name: CountBookmarks :one
SELECT COUNT(*) FROM bookmarks
WHERE owner = sqlc.arg(owner)
  AND (sqlc.arg(search) = '' OR (title LIKE '%' || sqlc.arg(search) || '%' OR link LIKE '%' || sqlc.arg(search) || '%'));

-- name: GetBookmark :one
SELECT * FROM bookmarks WHERE id = sqlc.arg(id) AND owner = sqlc.arg(owner);

-- name: CreateBookmark :one
INSERT INTO bookmarks (owner, title, link, notes, created_at, updated_at)
VALUES (sqlc.arg(owner), sqlc.arg(title), sqlc.arg(link), sqlc.arg(notes), sqlc.arg(now), sqlc.arg(now))
RETURNING id;

-- name: UpdateBookmarkBasics :exec
UPDATE bookmarks SET title = sqlc.arg(title), link = sqlc.arg(link), updated_at = sqlc.arg(now) WHERE id = sqlc.arg(id) AND owner = sqlc.arg(owner);

-- name: UpdateBookmarkAdvanced :exec
UPDATE bookmarks SET notes = sqlc.arg(notes), updated_at = sqlc.arg(now) WHERE id = sqlc.arg(id) AND owner = sqlc.arg(owner);

-- name: DeleteBookmark :exec
DELETE FROM bookmarks WHERE id = sqlc.arg(id) AND owner = sqlc.arg(owner);
`

var goldenScopedMigrationsGo = "// Code generated by rastrillo generate; DO NOT EDIT.\n" +
	"package bookmarksstore\n\n" +
	"// Migrations is the schema for Options.Migrations. Additive changes\n" +
	"// beyond this initial CREATE are the app's own migrations.\n" +
	"var Migrations = []string{" + bq + `CREATE TABLE IF NOT EXISTS bookmarks (
  id INTEGER PRIMARY KEY,
  owner TEXT NOT NULL,
  title TEXT NOT NULL DEFAULT '',
  link TEXT NOT NULL DEFAULT '',
  notes TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);` + bq + ", " + bq + "CREATE INDEX IF NOT EXISTS bookmarks_owner ON bookmarks (owner);" + bq + "}\n"

func TestEmitStoreScopedGoldenFiles(t *testing.T) {
	dir := t.TempDir()
	r := scopedFixtureResource()

	if _, err := EmitStore(dir, []rastrillo.Resource{r}); err != nil {
		t.Fatalf("EmitStore: %v", err)
	}

	cases := []struct {
		path string
		want string
	}{
		{filepath.Join(dir, "store", "bookmarks", "schema.sql"), goldenScopedSchemaSQL},
		{filepath.Join(dir, "store", "bookmarks", "queries.sql"), goldenScopedQueriesSQL},
		{filepath.Join(dir, "store", "bookmarks", "migrations.go"), goldenScopedMigrationsGo},
	}
	for _, c := range cases {
		got, err := os.ReadFile(c.path)
		if err != nil {
			t.Fatalf("read %s: %v", c.path, err)
		}
		if string(got) != c.want {
			t.Errorf("%s:\ngot:\n%s\nwant:\n%s", c.path, got, c.want)
		}
	}
}

func TestEmitStoreGoldenFiles(t *testing.T) {
	dir := t.TempDir()
	r := fixtureResource()

	if _, err := EmitStore(dir, []rastrillo.Resource{r}); err != nil {
		t.Fatalf("EmitStore: %v", err)
	}

	cases := []struct {
		path string
		want string
	}{
		{filepath.Join(dir, "store", "sqlc.yaml"), goldenSqlcYAML},
		{filepath.Join(dir, "store", "notes", "schema.sql"), goldenSchemaSQL},
		{filepath.Join(dir, "store", "notes", "queries.sql"), goldenQueriesSQL},
		{filepath.Join(dir, "store", "notes", "migrations.go"), goldenMigrationsGo},
	}
	for _, c := range cases {
		got, err := os.ReadFile(c.path)
		if err != nil {
			t.Fatalf("read %s: %v", c.path, err)
		}
		if string(got) != c.want {
			t.Errorf("%s:\ngot:\n%s\nwant:\n%s", c.path, got, c.want)
		}
	}
}

func TestEmitStoreReturnsEmittedPaths(t *testing.T) {
	dir := t.TempDir()
	r := fixtureResource()

	paths, err := EmitStore(dir, []rastrillo.Resource{r})
	if err != nil {
		t.Fatalf("EmitStore: %v", err)
	}
	want := []string{
		filepath.Join(dir, "store", "sqlc.yaml"),
		filepath.Join(dir, "store", "notes", "schema.sql"),
		filepath.Join(dir, "store", "notes", "queries.sql"),
		filepath.Join(dir, "store", "notes", "migrations.go"),
	}
	if len(paths) != len(want) {
		t.Fatalf("paths = %v, want %v", paths, want)
	}
	for i := range want {
		if paths[i] != want[i] {
			t.Errorf("paths[%d] = %q, want %q", i, paths[i], want[i])
		}
	}
}

func TestEmitStoreIsIdempotent(t *testing.T) {
	dir := t.TempDir()
	r := fixtureResource()

	paths, err := EmitStore(dir, []rastrillo.Resource{r})
	if err != nil {
		t.Fatalf("EmitStore (1st): %v", err)
	}
	first := readAllFiles(t, paths)

	if _, err := EmitStore(dir, []rastrillo.Resource{r}); err != nil {
		t.Fatalf("EmitStore (2nd): %v", err)
	}
	second := readAllFiles(t, paths)

	for _, p := range paths {
		if first[p] != second[p] {
			t.Errorf("%s changed between runs", p)
		}
	}
}

func readAllFiles(t *testing.T, paths []string) map[string]string {
	t.Helper()
	out := map[string]string{}
	for _, p := range paths {
		b, err := os.ReadFile(p)
		if err != nil {
			t.Fatalf("read %s: %v", p, err)
		}
		out[p] = string(b)
	}
	return out
}

func TestSqlName(t *testing.T) {
	cases := map[string]string{
		"Title":       "title",
		"Price":       "price",
		"Body":        "body",
		"MaxPerOrder": "max_per_order",
	}
	for in, want := range cases {
		if got := sqlName(in); got != want {
			t.Errorf("sqlName(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestSqlColumnTypeMoneyIsInteger(t *testing.T) {
	got := sqlColumnType(rastrillo.Money)
	if !strings.HasPrefix(got, "INTEGER") {
		t.Errorf("sqlColumnType(Money) = %q, want it to start with INTEGER", got)
	}
}

func TestSqlColumnTypeUnknownKindPanics(t *testing.T) {
	defer func() {
		if r := recover(); r == nil {
			t.Fatal("sqlColumnType(unknown kind) did not panic")
		}
	}()
	sqlColumnType(rastrillo.Kind("meter"))
}

const goldenEventsSchemaSql = `-- Code generated by rastrillo generate; DO NOT EDIT.
CREATE TABLE events (
  id INTEGER PRIMARY KEY,
  title TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
`

const goldenEventsQueriesSql = `-- Code generated by rastrillo generate; DO NOT EDIT.

-- name: ListEvents :many
SELECT * FROM events
WHERE (sqlc.arg(search) = '' OR (title LIKE '%' || sqlc.arg(search) || '%' OR status LIKE '%' || sqlc.arg(search) || '%'))
  AND (sqlc.arg(filter_status) = '' OR status = sqlc.arg(filter_status))
ORDER BY created_at DESC, id DESC
LIMIT sqlc.arg(page_limit) OFFSET sqlc.arg(page_offset);

-- name: CountEvents :one
SELECT COUNT(*) FROM events
WHERE (sqlc.arg(search) = '' OR (title LIKE '%' || sqlc.arg(search) || '%' OR status LIKE '%' || sqlc.arg(search) || '%'))
  AND (sqlc.arg(filter_status) = '' OR status = sqlc.arg(filter_status));

-- name: GetEvent :one
SELECT * FROM events WHERE id = sqlc.arg(id);

-- name: CreateEvent :one
INSERT INTO events (title, status, created_at, updated_at)
VALUES (sqlc.arg(title), sqlc.arg(status), sqlc.arg(now), sqlc.arg(now))
RETURNING id;

-- name: UpdateEventBasics :exec
UPDATE events SET title = sqlc.arg(title), status = sqlc.arg(status), updated_at = sqlc.arg(now) WHERE id = sqlc.arg(id);

-- name: DeleteEvent :exec
DELETE FROM events WHERE id = sqlc.arg(id);
`

func TestEmitStoreFiltersDeduped(t *testing.T) {
	dir := t.TempDir()
	r := filteredFixtureResource()

	if _, err := EmitStore(dir, []rastrillo.Resource{r}); err != nil {
		t.Fatalf("EmitStore: %v", err)
	}

	cases := []struct {
		path string
		want string
	}{
		{filepath.Join(dir, "store", "events", "schema.sql"), goldenEventsSchemaSql},
		{filepath.Join(dir, "store", "events", "queries.sql"), goldenEventsQueriesSql},
	}
	for _, c := range cases {
		got, err := os.ReadFile(c.path)
		if err != nil {
			t.Fatalf("read %s: %v", c.path, err)
		}
		if string(got) != c.want {
			t.Errorf("%s:\ngot:\n%s\nwant:\n%s", c.path, got, c.want)
		}
	}

	// Verify that filter_status appears in both List and Count queries but not duplicated
	// (when Status is in both Filter and Filters, the union should deduplicate it).
	// Each query has it twice: once in the empty-arg check, once in the value check.
	queriesBuf, err := os.ReadFile(filepath.Join(dir, "store", "events", "queries.sql"))
	if err != nil {
		t.Fatalf("read queries.sql: %v", err)
	}
	queriesText := string(queriesBuf)
	// Count occurrences of filter_status - should be 4 (2 in ListEvents, 2 in CountEvents)
	// because it appears in "(sqlc.arg(filter_status) = '' OR status = sqlc.arg(filter_status))"
	filterCount := strings.Count(queriesText, "sqlc.arg(filter_status)")
	if filterCount != 4 {
		t.Errorf("sqlc.arg(filter_status) appears %d times, want 4 (2 in ListEvents, 2 in CountEvents)", filterCount)
	}
}
