package generate

import (
	"bytes"
	"html/template"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"github.com/carlosframework/rastrillo"
	"github.com/carlosframework/rastrillo/ui"
)

// goldenListHTML is the brief's pinned golden for the fixture (which
// declares no List.Filters — Title is only a bare List.Filter entry):
// the generated list renders Search only — no "Filter" key on list-bar
// and no filter control. Kept BYTE-IDENTICAL by this task, on purpose:
// goldenFilteredListHTML below is the Filters-declared counterpart, and
// this constant staying pinned (TestEmitTemplatesGoldenFiles, run
// unmodified) is a no-Filters resource's regression gate.
const goldenListHTML = `{{/* Code generated by rastrillo generate; DO NOT EDIT.
     Eject: copy to templates/notes/list.html and edit — generation of
     this one file then stops. */}}
{{define "content"}}
{{template "page-header" dict "Title" (T "resource.notes.name") "ActionHref" "/admin/notes/new" "ActionLabel" (T "ui.new")}}
{{if .Empty}}
{{template "empty-state" dict "Title" (T "resource.notes.empty.title") "Body" (T "resource.notes.empty.body") "ActionHref" "/admin/notes/new" "ActionLabel" (T "ui.new")}}
{{else}}
<div class="rst-list">
{{template "list-bar" dict "SearchAction" "/admin/notes" "Query" .Query "Placeholder" (T "ui.search") "Hidden" .Carry}}
{{range .Rows}}{{template "list-row-action" dict "Href" .Href "Main" .Main "Sub" .Sub}}
{{end}}
</div>
{{if .Pagination.Show}}{{template "pagination" dict "Items" .Pagination.Items}}{{end}}
{{end}}
{{end}}
`

// goldenShowHTML: page-header (record's first text field as Title, edit
// action pill) + detail-list over every declared field, in the fixture's
// columns() order (Title, Price, Body — List columns first, then Form
// fields not already present). Money (Price) renders Mono, since it is
// a formatted-currency string, not prose.
const goldenShowHTML = `{{/* Code generated by rastrillo generate; DO NOT EDIT.
     Eject: copy to templates/notes/show.html and edit — generation of
     this one file then stops.

     Data contract (the action emitter reads this):
       Title     string, required — the record shown here (its first
                 text field's value; list.html's Main, restated for the
                 header)
       EditHref  string, required — this record's edit route
       Fields    map[string]string, required — every declared field's
                 value keyed by its declared name, in this resource's
                 declaration order: Title, Price, Body. Money is
                 already formatted as a dollar string by the action —
                 templates never do money math. */}}
{{define "content"}}
{{template "page-header" dict "Title" .Title "ActionHref" .EditHref "ActionLabel" (T "ui.edit")}}
{{template "detail-list" dict "Items" (list
  (dict "Label" (T "resource.notes.field.title") "Value" .Fields.Title)
  (dict "Label" (T "resource.notes.field.price") "Value" .Fields.Price "Mono" true)
  (dict "Label" (T "resource.notes.field.body") "Value" .Fields.Body)
)}}
{{end}}
`

// goldenFormHTML: New posts Basics+Advanced as one form to the create
// route (r.Route); Edit posts Basics to .BasicsAction and, because the
// fixture's Advanced is non-empty, a second form posts Advanced to
// .AdvancedAction. Money (Price) renders as field-text — templates
// never do money math, the action already formatted the value.
const goldenFormHTML = `{{/* Code generated by rastrillo generate; DO NOT EDIT.
     Eject: copy to templates/notes/form.html and edit — generation of
     this one file then stops.

     Data contract (the action emitter reads this):
       IsNew           bool, required — New renders one form posting
                       every field to the create route; Edit renders
                       Basics (and, when this resource declares
                       Advanced fields, a second Advanced form)
       Fields          map[string]string, required — current values
                       keyed by declared field name; Money already
                       formatted as a dollar string by the action
                       (templates never do money math); empty strings
                       for New
       Errors          map[string]string, optional — a validation
                       message per field name, set only on a 400
                       re-render
       BasicsAction    string, required when !IsNew — the
                       edit-basics POST target
       AdvancedAction  string, required when !IsNew — the
                       edit-advanced POST target */}}
{{define "content"}}
{{if .IsNew}}
<form class="rst-form" method="post" action="/admin/notes">
{{template "field-text" dict "Name" "Title" "Label" (T "resource.notes.field.title") "Value" .Fields.Title "Error" .Errors.Title}}
{{template "field-textarea" dict "Name" "Body" "Label" (T "resource.notes.field.body") "Value" .Fields.Body "Error" .Errors.Body}}
{{template "field-text" dict "Name" "Price" "Label" (T "resource.notes.field.price") "Value" .Fields.Price "Error" .Errors.Price}}
{{template "form-foot" dict "Submit" (T "ui.save") "CancelHref" "/admin/notes" "CancelLabel" (T "ui.cancel")}}
</form>
{{else}}
<form class="rst-form" method="post" action="{{.BasicsAction}}">
{{template "field-text" dict "Name" "Title" "Label" (T "resource.notes.field.title") "Value" .Fields.Title "Error" .Errors.Title}}
{{template "field-textarea" dict "Name" "Body" "Label" (T "resource.notes.field.body") "Value" .Fields.Body "Error" .Errors.Body}}
{{template "form-foot" dict "Submit" (T "ui.save") "CancelHref" "/admin/notes" "CancelLabel" (T "ui.cancel")}}
</form>
<form class="rst-form" method="post" action="{{.AdvancedAction}}">
{{template "field-text" dict "Name" "Price" "Label" (T "resource.notes.field.price") "Value" .Fields.Price "Error" .Errors.Price}}
{{template "form-foot" dict "Submit" (T "ui.save") "CancelHref" "/admin/notes" "CancelLabel" (T "ui.cancel")}}
</form>
{{end}}
{{end}}
`

// noSearchFixtureResource is a minimal resource with List.Search false
// (and no Filter) — the path the fixtureResource() golden never
// exercises, since it always has Search: true. Used to prove list-bar
// is gated on List.Search at generation time, not rendered
// unconditionally.
func noSearchFixtureResource() rastrillo.Resource {
	r := rastrillo.Resource{
		Name:  "widgets",
		Route: "/admin/widgets",
		Store: rastrillo.Exclusive,
		List: rastrillo.List{
			Columns: []rastrillo.Column{{Field: "Name"}},
			Search:  false,
		},
		Form: rastrillo.Form{
			Basics: []rastrillo.Field{{Name: "Name"}},
		},
	}
	if err := r.Validate(); err != nil {
		panic(err)
	}
	return r
}

// TestEmitTemplatesListHTMLGatesSearchOnFlag is the fix for a reviewer
// finding: list.html used to render the search box unconditionally,
// even though the generated store's WHERE clause only honors `q` when
// List.Search is true (whereClauses in store.go) — a search=false
// resource got a live-looking input that silently did nothing. list-bar
// is now gated on r.List.Search at GENERATION time (mirroring how
// hasAdvanced gates form.html's second form): a search=false resource's
// list.html contains no list-bar at all.
func TestEmitTemplatesListHTMLGatesSearchOnFlag(t *testing.T) {
	appRoot := t.TempDir()
	genDir := t.TempDir()
	r := noSearchFixtureResource()

	if _, _, err := EmitTemplates(appRoot, genDir, r); err != nil {
		t.Fatalf("EmitTemplates: %v", err)
	}

	got, err := os.ReadFile(filepath.Join(genDir, "templates", "widgets", "list.html"))
	if err != nil {
		t.Fatalf("read list.html: %v", err)
	}
	if strings.Contains(string(got), "list-bar") {
		t.Errorf("list.html contains \"list-bar\" for a Search: false resource:\n%s", got)
	}
	if strings.Contains(string(got), "rst-search") {
		t.Errorf("list.html contains \"rst-search\" for a Search: false resource:\n%s", got)
	}
	// The rows and the rst-list card wrapper must still be there — only
	// the search box is gone.
	if !strings.Contains(string(got), `<div class="rst-list">`) {
		t.Errorf("list.html lost its rst-list wrapper:\n%s", got)
	}
	if !strings.Contains(string(got), `{{range .Rows}}`) {
		t.Errorf("list.html lost its row range:\n%s", got)
	}
}

// goldenFilteredListHTML is EmitTemplates' list.html for
// filteredFixtureResource() (Status: bare List.Filter AND a
// List.Filters entry with Values draft/live, Search on): the rst-lbar
// strip is hand-composed (list-bar-search plus the inline dropdown
// block) rather than one "list-bar" dispatch — see listHTML's doc
// comment for why. The dropdown block's classes/attributes/whitespace
// trims mirror ui/partials/dropdown.html's own template text exactly
// (TestListHTMLDropdownMatchesPartial below proves the two render
// byte-identical markup given the same resolved strings), with (T
// .LabelKey) standing in for dropdown.html's plain .Label and the
// summary's aria-label composed inline from (T .Filter.AriaField) and
// (T .Filter.SummaryKey) — every label a T KEY, resolved only at
// Execute time (see the package doc's "labels resolve at RENDER time"
// note).
const goldenFilteredListHTML = `{{/* Code generated by rastrillo generate; DO NOT EDIT.
     Eject: copy to templates/events/list.html and edit — generation of
     this one file then stops. */}}
{{define "content"}}
{{template "page-header" dict "Title" (T "resource.events.name") "ActionHref" "/admin/events/new" "ActionLabel" (T "ui.new")}}
{{if .Empty}}
{{template "empty-state" dict "Title" (T "resource.events.empty.title") "Body" (T "resource.events.empty.body") "ActionHref" "/admin/events/new" "ActionLabel" (T "ui.new")}}
{{else}}
<div class="rst-list">
<div class="rst-lbar">
{{template "list-bar-search" dict "Action" "/admin/events" "Query" .Query "Placeholder" (T "ui.search") "Hidden" .Carry}}
{{/* dropdown markup inlined, not dispatched via the "dropdown" partial:
     per-item (T .LabelKey) resolution inside this range cannot be
     expressed as a single dict/list argument to one {{template}} call
     (see listHTML's doc comment). Keep this block structurally
     identical to ui/partials/dropdown.html — same classes, same
     aria-current/check-icon guards, same whitespace trims — so the
     existing CSS and a11y contract hold unchanged. */}}
<details class="rst-dropdown">
  <summary class="rst-btn rst-dropdown__summary" aria-label="Filter by {{T .Filter.AriaField}}: {{T .Filter.SummaryKey}}">{{T .Filter.SummaryKey}} {{icon "chevron-down"}}</summary>
  <div class="rst-dropdown__menu">
    {{- range .Filter.Items}}
    <a href="{{.Href}}"{{if .Current}} aria-current="true"{{end}}>{{T .LabelKey}}{{if .Current}} {{icon "check"}}{{end}}</a>
    {{- end}}
  </div>
</details>
</div>
{{range .Rows}}{{template "list-row-action" dict "Href" .Href "Main" .Main "Sub" .Sub}}
{{end}}
</div>
{{if .Pagination.Show}}{{template "pagination" dict "Items" .Pagination.Items}}{{end}}
{{end}}
{{end}}
`

// TestEmitTemplatesFilteredListHTMLGolden pins EmitTemplates' list.html
// for filteredFixtureResource() against goldenFilteredListHTML — the
// Filters-declared counterpart to TestEmitTemplatesGoldenFiles'
// goldenListHTML, which stays pinned against fixtureResource() (no
// List.Filters) completely unchanged by this task.
func TestEmitTemplatesFilteredListHTMLGolden(t *testing.T) {
	appRoot := t.TempDir()
	genDir := t.TempDir()
	r := filteredFixtureResource()

	if _, _, err := EmitTemplates(appRoot, genDir, r); err != nil {
		t.Fatalf("EmitTemplates: %v", err)
	}

	path := filepath.Join(genDir, "templates", "events", "list.html")
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	if string(got) != goldenFilteredListHTML {
		t.Errorf("%s:\ngot:\n%s\nwant:\n%s", path, got, goldenFilteredListHTML)
	}
}

// TestListHTMLDropdownMatchesPartial is the brief's markup-equivalence
// test: it renders the inline <details class="rst-dropdown"> block
// listHTML emits for a Filters-declared resource and separately renders
// the real "dropdown" partial (ui/partials/dropdown.html) given the
// SAME already-resolved Label/Aria strings the inline block's (T
// .LabelKey) / (T .Filter.AriaField) / (T .Filter.SummaryKey) calls
// would produce, then asserts the two render byte-identical HTML — the
// binding decision's whole premise (same classes, same a11y contract)
// only holds if this stays true.
func TestListHTMLDropdownMatchesPartial(t *testing.T) {
	appRoot := t.TempDir()
	genDir := t.TempDir()
	r := filteredFixtureResource()

	if _, _, err := EmitTemplates(appRoot, genDir, r); err != nil {
		t.Fatalf("EmitTemplates: %v", err)
	}

	// tKeys is the resolved-string counterpart to what the generated
	// action's filterView actually carries as KEYS (see actions.go):
	// ui.all, resource.events.field.status, and one
	// resource.events.filter.status.<value> per declared value.
	tKeys := map[string]string{
		"ui.all":                              "All",
		"resource.events.field.status":        "Status",
		"resource.events.filter.status.draft": "Drafts",
		"resource.events.filter.status.live":  "Live",
	}
	T := func(k string) string {
		if v, ok := tKeys[k]; ok {
			return v
		}
		return k
	}

	tmpl := template.New("").Funcs(ui.Funcs()).Funcs(template.FuncMap{"T": T})
	tmpl, err := tmpl.ParseFS(ui.Templates(), "*.html")
	if err != nil {
		t.Fatalf("parse ui templates: %v", err)
	}
	// list.html alone, not a glob of the whole events/ directory: show.html
	// and form.html each define their OWN "content" template too (the
	// three screens share that one name deliberately — see
	// buildPages' own doc in examples/blog/internal/blog/render.go), and
	// parsing more than one into a single tree would let whichever file
	// sorts last silently clobber list.html's "content" definition.
	tmpl, err = tmpl.ParseFiles(filepath.Join(genDir, "templates", "events", "list.html"))
	if err != nil {
		t.Fatalf("parse emitted list.html: %v", err)
	}

	type filterItem struct {
		Href     string
		LabelKey string
		Current  bool
	}
	type filterView struct {
		SummaryKey string
		AriaField  string
		Items      []filterItem
	}
	data := struct {
		Empty      bool
		Query      string
		Carry      [][2]string
		Filter     filterView
		Rows       []struct{ Href, Main, Sub string }
		Pagination struct {
			Show  bool
			Items []struct{}
		}
	}{
		Filter: filterView{
			// The applied value: draft. Exercises Current on a real
			// (non-All) item as well as the All item's Current == false.
			SummaryKey: "resource.events.filter.status.draft",
			AriaField:  "resource.events.field.status",
			Items: []filterItem{
				{Href: "/admin/events", LabelKey: "ui.all", Current: false},
				{Href: "/admin/events?status=draft", LabelKey: "resource.events.filter.status.draft", Current: true},
				{Href: "/admin/events?status=live", LabelKey: "resource.events.filter.status.live", Current: false},
			},
		},
	}

	var buf bytes.Buffer
	if err := tmpl.ExecuteTemplate(&buf, "content", data); err != nil {
		t.Fatalf("execute content: %v", err)
	}

	re := regexp.MustCompile(`(?s)<details class="rst-dropdown">.*?</details>`)
	got := re.FindString(buf.String())
	if got == "" {
		t.Fatalf("no <details class=%q> block found in rendered content:\n%s", "rst-dropdown", buf.String())
	}

	partialData := map[string]any{
		"Label": "Drafts",
		"Aria":  "Filter by Status: Drafts",
		"Items": []map[string]any{
			{"Href": "/admin/events", "Label": "All", "Current": false},
			{"Href": "/admin/events?status=draft", "Label": "Drafts", "Current": true},
			{"Href": "/admin/events?status=live", "Label": "Live", "Current": false},
		},
	}
	var want bytes.Buffer
	if err := tmpl.ExecuteTemplate(&want, "dropdown", partialData); err != nil {
		t.Fatalf("execute dropdown partial: %v", err)
	}

	if got != want.String() {
		t.Errorf("inline dropdown block does not match the real partial's render:\ngot:\n%s\nwant:\n%s", got, want.String())
	}
}

// goldenFilteredFormHTML is EmitTemplates' form.html for
// filteredFixtureResource() (Title: Required, Status: not — no Advanced
// fields at all, so only the New-form and the single Basics form
// render, never a second Advanced form): Title's field-text call gains
// "Required" true; Status's does not — pinning that formField only adds
// the key for the ONE field that declares it, and only there, both in
// the New form (which renders every field once) and the Edit/Basics
// form (which renders the same field again). goldenFormHTML above (no
// Required field in the fixture it renders) stays byte-identical,
// unmodified by this task — the regression gate for a resource with no
// Required fields.
const goldenFilteredFormHTML = `{{/* Code generated by rastrillo generate; DO NOT EDIT.
     Eject: copy to templates/events/form.html and edit — generation of
     this one file then stops.

     Data contract (the action emitter reads this):
       IsNew           bool, required — New renders one form posting
                       every field to the create route; Edit renders
                       Basics (and, when this resource declares
                       Advanced fields, a second Advanced form)
       Fields          map[string]string, required — current values
                       keyed by declared field name; Money already
                       formatted as a dollar string by the action
                       (templates never do money math); empty strings
                       for New
       Errors          map[string]string, optional — a validation
                       message per field name, set only on a 400
                       re-render
       BasicsAction    string, required when !IsNew — the
                       edit-basics POST target (this resource has
                       no Advanced fields, so there is no second
                       form) */}}
{{define "content"}}
{{if .IsNew}}
<form class="rst-form" method="post" action="/admin/events">
{{template "field-text" dict "Name" "Title" "Label" (T "resource.events.field.title") "Value" .Fields.Title "Error" .Errors.Title "Required" true}}
{{template "field-text" dict "Name" "Status" "Label" (T "resource.events.field.status") "Value" .Fields.Status "Error" .Errors.Status}}
{{template "form-foot" dict "Submit" (T "ui.save") "CancelHref" "/admin/events" "CancelLabel" (T "ui.cancel")}}
</form>
{{else}}
<form class="rst-form" method="post" action="{{.BasicsAction}}">
{{template "field-text" dict "Name" "Title" "Label" (T "resource.events.field.title") "Value" .Fields.Title "Error" .Errors.Title "Required" true}}
{{template "field-text" dict "Name" "Status" "Label" (T "resource.events.field.status") "Value" .Fields.Status "Error" .Errors.Status}}
{{template "form-foot" dict "Submit" (T "ui.save") "CancelHref" "/admin/events" "CancelLabel" (T "ui.cancel")}}
</form>
{{end}}
{{end}}
`

// TestEmitTemplatesFilteredFormHTMLGolden pins EmitTemplates' form.html
// for filteredFixtureResource() against goldenFilteredFormHTML — the
// Required counterpart to TestEmitTemplatesGoldenFiles' goldenFormHTML,
// which stays pinned against fixtureResource() (no Required field)
// completely unchanged by this task.
func TestEmitTemplatesFilteredFormHTMLGolden(t *testing.T) {
	appRoot := t.TempDir()
	genDir := t.TempDir()
	r := filteredFixtureResource()

	if _, _, err := EmitTemplates(appRoot, genDir, r); err != nil {
		t.Fatalf("EmitTemplates: %v", err)
	}

	path := filepath.Join(genDir, "templates", "events", "form.html")
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	if string(got) != goldenFilteredFormHTML {
		t.Errorf("%s:\ngot:\n%s\nwant:\n%s", path, got, goldenFilteredFormHTML)
	}
}

func TestEmitTemplatesGoldenFiles(t *testing.T) {
	appRoot := t.TempDir()
	genDir := t.TempDir()
	r := fixtureResource()

	written, skipped, err := EmitTemplates(appRoot, genDir, r)
	if err != nil {
		t.Fatalf("EmitTemplates: %v", err)
	}
	if len(skipped) != 0 {
		t.Fatalf("skipped = %v, want none", skipped)
	}
	wantWritten := []string{
		filepath.Join(genDir, "templates", "notes", "list.html"),
		filepath.Join(genDir, "templates", "notes", "show.html"),
		filepath.Join(genDir, "templates", "notes", "form.html"),
	}
	if len(written) != len(wantWritten) {
		t.Fatalf("written = %v, want %v", written, wantWritten)
	}
	for i := range wantWritten {
		if written[i] != wantWritten[i] {
			t.Errorf("written[%d] = %q, want %q", i, written[i], wantWritten[i])
		}
	}

	cases := []struct {
		path string
		want string
	}{
		{filepath.Join(genDir, "templates", "notes", "list.html"), goldenListHTML},
		{filepath.Join(genDir, "templates", "notes", "show.html"), goldenShowHTML},
		{filepath.Join(genDir, "templates", "notes", "form.html"), goldenFormHTML},
	}
	for _, c := range cases {
		got, err := os.ReadFile(c.path)
		if err != nil {
			t.Fatalf("read %s: %v", c.path, err)
		}
		if string(got) != c.want {
			t.Errorf("%s:\ngot:\n%s\nwant:\n%s", c.path, got, c.want)
		}
	}
}

func TestEmitTemplatesIsIdempotent(t *testing.T) {
	appRoot := t.TempDir()
	genDir := t.TempDir()
	r := fixtureResource()

	written, _, err := EmitTemplates(appRoot, genDir, r)
	if err != nil {
		t.Fatalf("EmitTemplates (1st): %v", err)
	}
	first := readAllFiles(t, written)

	if _, _, err := EmitTemplates(appRoot, genDir, r); err != nil {
		t.Fatalf("EmitTemplates (2nd): %v", err)
	}
	second := readAllFiles(t, written)

	for _, p := range written {
		if first[p] != second[p] {
			t.Errorf("%s changed between runs", p)
		}
	}
}

func TestEmitTemplatesSkipsEjectedFiles(t *testing.T) {
	appRoot := t.TempDir()
	genDir := t.TempDir()
	r := fixtureResource()

	handDir := filepath.Join(appRoot, "templates", "notes")
	if err := os.MkdirAll(handDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(handDir, "list.html"), []byte("hand-written"), 0o644); err != nil {
		t.Fatal(err)
	}

	written, skipped, err := EmitTemplates(appRoot, genDir, r)
	if err != nil {
		t.Fatalf("EmitTemplates: %v", err)
	}

	wantSkipped := []string{filepath.Join(genDir, "templates", "notes", "list.html")}
	if len(skipped) != 1 || skipped[0] != wantSkipped[0] {
		t.Fatalf("skipped = %v, want %v", skipped, wantSkipped)
	}
	if _, err := os.Stat(filepath.Join(genDir, "templates", "notes", "list.html")); !os.IsNotExist(err) {
		t.Fatalf("list.html was written into genDir despite the hand file")
	}

	wantWritten := []string{
		filepath.Join(genDir, "templates", "notes", "show.html"),
		filepath.Join(genDir, "templates", "notes", "form.html"),
	}
	if len(written) != len(wantWritten) {
		t.Fatalf("written = %v, want %v", written, wantWritten)
	}
	for i := range wantWritten {
		if written[i] != wantWritten[i] {
			t.Errorf("written[%d] = %q, want %q", i, written[i], wantWritten[i])
		}
	}
}

// TestEmittedTemplatesParse proves the emitted files compile as
// templates in exactly the environment the app provides them: ui's
// partials plus ui.Funcs() (dict/list/icon), plus a stubbed T (the app
// binds the real one per locale at request time; see localemw.go).
func TestEmittedTemplatesParse(t *testing.T) {
	appRoot := t.TempDir()
	genDir := t.TempDir()
	r := fixtureResource()

	if _, _, err := EmitTemplates(appRoot, genDir, r); err != nil {
		t.Fatalf("EmitTemplates: %v", err)
	}

	tmpl := template.New("").Funcs(ui.Funcs()).Funcs(template.FuncMap{
		"T": func(s string) string { return s },
	})
	tmpl, err := tmpl.ParseFS(ui.Templates(), "*.html")
	if err != nil {
		t.Fatalf("parse ui templates: %v", err)
	}
	tmpl, err = tmpl.ParseGlob(filepath.Join(genDir, "templates", "notes", "*.html"))
	if err != nil {
		t.Fatalf("parse emitted templates: %v", err)
	}
	if tmpl.Lookup("content") == nil {
		t.Fatalf("no \"content\" template defined after parsing")
	}
}

func TestEmitTemplatesUnknownKindPanics(t *testing.T) {
	defer func() {
		if recover() == nil {
			t.Fatal("expected panic for unknown Kind")
		}
	}()
	r := fixtureResource()
	r.Form.Basics[0].Kind = rastrillo.Kind("bogus")
	_, _, _ = EmitTemplates(t.TempDir(), t.TempDir(), r)
}
